#!/usr/bin/env python3

# Runs a command with CX_ABORT_ON_THROW=1.

import os
import subprocess
import sys

env = dict(os.environ)
env["CX_ABORT_ON_THROW"] = "1"

sys.exit(subprocess.call(sys.argv[1:], env=env))
