#!/usr/bin/env python

import os
import sys
import subprocess


def convert_newlines(string):
    return string.replace("\r\n", "\n")


snapshot_path = sys.argv[1]

try:
    output = subprocess.check_output(sys.argv[2:])
except subprocess.CalledProcessError as error:
    print(error.output)
    sys.exit(error.returncode)

if "UPDATE_SNAPSHOTS" in os.environ:
    with open(snapshot_path, "w") as snapshot_file:
        snapshot_file.write(output)
    sys.exit(0)

with open(snapshot_path, "r") as snapshot_file:
    snapshot = convert_newlines(snapshot_file.read())

if output != snapshot:
    print("FAIL: output doesn't match snapshot\n")
    print("- Snapshot")
    print("+ Received\n")

    import difflib
    diff = difflib.unified_diff(snapshot.splitlines(1), output.splitlines(1))
    print("".join(diff))

    sys.exit(1)
