#!/usr/bin/env python

import sys
import subprocess

expected_exit_status = int(sys.argv[1])
actual_exit_status = subprocess.call(sys.argv[2:])

if actual_exit_status != expected_exit_status:
    print("FAIL: expected exit status: {}, actual exit status: {}".format(expected_exit_status, actual_exit_status))
    sys.exit(1)
