#!/usr/bin/env python

import os
import subprocess
import sys


def convert_newlines(string):
    return string.replace("\r\n", "\n")


test_file = sys.argv[2]
checks = [
    ('-print-ir', '.ir'),
    ('-print-llvm', '.ll'),
]

for compiler_flag, extension in checks:
    snapshot_path = test_file + extension

    try:
        output = subprocess.check_output(sys.argv[1:] + [compiler_flag], text=True)
    except subprocess.CalledProcessError as error:
        print(error.output)
        sys.exit(error.returncode)

    if "UPDATE_SNAPSHOTS" in os.environ:
        with open(snapshot_path, "w") as snapshot_file:
            snapshot_file.write(output)
        continue

    try:
        with open(snapshot_path, "r") as snapshot_file:
            snapshot = convert_newlines(snapshot_file.read())
    except IOError:
        print("FAIL: snapshot file not found\n")
        print("Output:")
        print(output)
        sys.exit(1)

    if output != snapshot:
        print("FAIL: output doesn't match snapshot\n")
        print("- Snapshot")
        print("+ Received\n")

        import difflib

        diff = difflib.unified_diff(snapshot.splitlines(1), output.splitlines(1))
        print("".join(diff))

        sys.exit(1)
