#!/usr/bin/env python

import os
import subprocess
import sys


def convert_newlines(string):
    return string.replace("\r\n", "\n")


allow_empty = '-allow-empty' in sys.argv
if allow_empty: sys.argv.remove('-allow-empty')

snapshot_path = sys.argv[1]

try:
    output = subprocess.check_output(sys.argv[2:])
except subprocess.CalledProcessError as error:
    print(error.output)
    sys.exit(error.returncode)

if output == "" and not allow_empty:
    print("FAIL: output was empty")
    sys.exit(1)

if "UPDATE_SNAPSHOTS" in os.environ:
    with open(snapshot_path, "w") as snapshot_file:
        snapshot_file.write(output)
    sys.exit(0)

try:
    with open(snapshot_path, "r") as snapshot_file:
        snapshot = convert_newlines(snapshot_file.read())
except IOError:
    print("FAIL: snapshot file not found\n")
    print("Output:")
    print(output)
    sys.exit(1)

if output != snapshot:
    print("FAIL: output doesn't match snapshot\n")
    print("- Snapshot")
    print("+ Received\n")

    import difflib

    diff = difflib.unified_diff(snapshot.splitlines(1), output.splitlines(1))
    print("".join(diff))

    sys.exit(1)
