
%X = type { i32, ptr }
%Empty = type {}
%"Generic<float32>" = type { float }
%"Generic<Empty>" = type { %Empty }

define i32 @main() #0 !dbg !4 {
  %b = alloca i32, align 4
  %x = alloca %X, align 8
  %y = alloca %X, align 8
  %e = alloca %Empty, align 8
  %g = alloca %"Generic<float32>", align 8
  %h = alloca %"Generic<Empty>", align 8
  store i32 2, ptr %b, align 4
  call void @_CX1N4mainM4main1X4initE4void2_M3std5int32PM3std5int32(ptr %x, i32 4, ptr %b), !dbg !7
  call void @_CX1N4mainM4main1X4initE4void2_M3std5int32PM3std5int32(ptr %y, i32 4, ptr %b), !dbg !8
  call void @_CX1N4mainM4main5Empty4initE4void0_(ptr %e), !dbg !9
  call void @_CX1N4mainM4main7GenericIM3std7float32E4initE4void1_M3std7float32(ptr %g, float 4.500000e+00), !dbg !10
  %e.load = load %Empty, ptr %e, align 1
  call void @_CX1N4mainM4main7GenericIM4main5EmptyE4initE4void1_M4main5Empty(ptr %h, %Empty %e.load), !dbg !11
  call void @_CX1N4mainM4main7GenericIM4main5EmptyE6deinitE4void0_(ptr %h), !dbg !12
  ret i32 0
}

define void @_CX1N4mainM4main1X4initE4void2_M3std5int32PM3std5int32(ptr %this, i32 %a, ptr %b) #0 !dbg !13 {
  %a1 = alloca i32, align 4
  %b2 = alloca ptr, align 8
  store i32 %a, ptr %a1, align 4
  store ptr %b, ptr %b2, align 8
  %a3 = getelementptr inbounds %X, ptr %this, i32 0, i32 0
  %a.load = load i32, ptr %a1, align 4
  store i32 %a.load, ptr %a3, align 4
  %b4 = getelementptr inbounds %X, ptr %this, i32 0, i32 1
  %b.load = load ptr, ptr %b2, align 8
  store ptr %b.load, ptr %b4, align 8
  ret void
}

define void @_CX1N4mainM4main5Empty4initE4void0_(ptr %this) #0 !dbg !14 {
  ret void
}

define void @_CX1N4mainM4main7GenericIM3std7float32E4initE4void1_M3std7float32(ptr %this, float %i) #0 !dbg !15 {
  %i1 = alloca float, align 4
  store float %i, ptr %i1, align 4
  %i2 = getelementptr inbounds %"Generic<float32>", ptr %this, i32 0, i32 0
  %i.load = load float, ptr %i1, align 4
  store float %i.load, ptr %i2, align 4
  ret void
}

define void @_CX1N4mainM4main7GenericIM4main5EmptyE4initE4void1_M4main5Empty(ptr %this, %Empty %i) #0 !dbg !16 {
  %i1 = alloca %Empty, align 8
  store %Empty %i, ptr %i1, align 1
  %i2 = getelementptr inbounds %"Generic<Empty>", ptr %this, i32 0, i32 0
  %i.load = load %Empty, ptr %i1, align 1
  store %Empty %i.load, ptr %i2, align 1
  ret void
}

define void @_CX1N4mainM4main7GenericIM4main5EmptyE6deinitE4void0_(ptr %this) #0 !dbg !17 {
  %i = getelementptr inbounds %"Generic<Empty>", ptr %this, i32 0, i32 0
  call void @_CX1N4mainM4main5Empty6deinitE4void0_(ptr %i), !dbg !18
  ret void
}

define void @_CX1N4mainM4main5Empty6deinitE4void0_(ptr %this) #0 !dbg !19 {
  ret void
}

attributes #0 = { "frame-pointer"="all" }

!llvm.module.flags = !{!0, !1}
!llvm.dbg.cu = !{!2}

!0 = !{i32 2, !"Dwarf Version", i32 4}
!1 = !{i32 2, !"Debug Info Version", i32 3}
!2 = distinct !DICompileUnit(language: DW_LANG_C, file: !3, producer: "cx", isOptimized: false, runtimeVersion: 0, emissionKind: FullDebug)
!3 = !DIFile(filename: "constructor-autogenerated.cx")
!4 = distinct !DISubprogram(name: "main", linkageName: "main", scope: !3, file: !3, line: 3, type: !5, scopeLine: 3, spFlags: DISPFlagDefinition, unit: !2)
!5 = !DISubroutineType(types: !6)
!6 = !{}
!7 = !DILocation(line: 5, column: 13, scope: !4)
!8 = !DILocation(line: 6, column: 13, scope: !4)
!9 = !DILocation(line: 7, column: 13, scope: !4)
!10 = !DILocation(line: 8, column: 13, scope: !4)
!11 = !DILocation(line: 9, column: 13, scope: !4)
!12 = !DILocation(line: 3, column: 6, scope: !4)
!13 = distinct !DISubprogram(name: "init", linkageName: "_CX1N4mainM4main1X4initE4void2_M3std5int32PM3std5int32", scope: !3, file: !3, line: 12, type: !5, scopeLine: 12, spFlags: DISPFlagDefinition, unit: !2)
!14 = distinct !DISubprogram(name: "init", linkageName: "_CX1N4mainM4main5Empty4initE4void0_", scope: !3, file: !3, line: 17, type: !5, scopeLine: 17, spFlags: DISPFlagDefinition, unit: !2)
!15 = distinct !DISubprogram(name: "init", linkageName: "_CX1N4mainM4main7GenericIM3std7float32E4initE4void1_M3std7float32", scope: !3, file: !3, line: 21, type: !5, scopeLine: 21, spFlags: DISPFlagDefinition, unit: !2)
!16 = distinct !DISubprogram(name: "init", linkageName: "_CX1N4mainM4main7GenericIM4main5EmptyE4initE4void1_M4main5Empty", scope: !3, file: !3, line: 21, type: !5, scopeLine: 21, spFlags: DISPFlagDefinition, unit: !2)
!17 = distinct !DISubprogram(name: "deinit", linkageName: "_CX1N4mainM4main7GenericIM4main5EmptyE6deinitE4void0_", scope: !3, file: !3, line: 21, type: !5, scopeLine: 21, spFlags: DISPFlagDefinition, unit: !2)
!18 = !DILocation(line: 21, column: 8, scope: !17)
!19 = distinct !DISubprogram(name: "deinit", linkageName: "_CX1N4mainM4main5Empty6deinitE4void0_", scope: !3, file: !3, line: 18, type: !5, scopeLine: 18, spFlags: DISPFlagDefinition, unit: !2)
