
%Color = type { i8, i8, i8 }
%Rectangle = type { float, float, float, float }

define i32 @main() #0 !dbg !4 {
  %c = alloca %Color, align 8
  %r = alloca %Rectangle, align 8
  call void @_CX1N43constructor_2Dautogenerated_2Dc_2Dimport__hM43constructor_2Dautogenerated_2Dc_2Dimport__h5Color4initE4void3_M3std5uint8M3std5uint8M3std5uint8(ptr %c, i8 1, i8 2, i8 3), !dbg !7
  call void @_CX1N43constructor_2Dautogenerated_2Dc_2Dimport__hM43constructor_2Dautogenerated_2Dc_2Dimport__h9Rectangle4initE4void4_M3std7float32M3std7float32M3std7float32M3std7float32(ptr %r, float 1.000000e+00, float 2.000000e+00, float 3.000000e+00, float 4.000000e+00), !dbg !8
  ret i32 0
}

declare void @_CX1N43constructor_2Dautogenerated_2Dc_2Dimport__hM43constructor_2Dautogenerated_2Dc_2Dimport__h5Color4initE4void3_M3std5uint8M3std5uint8M3std5uint8(ptr, i8, i8, i8) #0

declare void @_CX1N43constructor_2Dautogenerated_2Dc_2Dimport__hM43constructor_2Dautogenerated_2Dc_2Dimport__h9Rectangle4initE4void4_M3std7float32M3std7float32M3std7float32M3std7float32(ptr, float, float, float, float) #0

attributes #0 = { "frame-pointer"="all" }

!llvm.module.flags = !{!0, !1}
!llvm.dbg.cu = !{!2}

!0 = !{i32 2, !"Dwarf Version", i32 4}
!1 = !{i32 2, !"Debug Info Version", i32 3}
!2 = distinct !DICompileUnit(language: DW_LANG_C, file: !3, producer: "cx", isOptimized: false, runtimeVersion: 0, emissionKind: FullDebug)
!3 = !DIFile(filename: "constructor-autogenerated-c-import.cx")
!4 = distinct !DISubprogram(name: "main", linkageName: "main", scope: !3, file: !3, line: 5, type: !5, scopeLine: 5, spFlags: DISPFlagDefinition, unit: !2)
!5 = !DISubroutineType(types: !6)
!6 = !{}
!7 = !DILocation(line: 6, column: 13, scope: !4)
!8 = !DILocation(line: 7, column: 13, scope: !4)
