
%Color = type { i8, i8, i8 }
%Rectangle = type { float, float, float, float }

define i32 @main() {
  %c = alloca %Color, align 8
  %r = alloca %Rectangle, align 8
  call void @_EN36constructor-autogenerated-c-import_h5Color4initE5uint85uint85uint8(ptr %c, i8 1, i8 2, i8 3)
  call void @_EN36constructor-autogenerated-c-import_h9Rectangle4initE5float5float5float5float(ptr %r, float 1.000000e+00, float 2.000000e+00, float 3.000000e+00, float 4.000000e+00)
  ret i32 0
}

define void @_EN36constructor-autogenerated-c-import_h5Color4initE5uint85uint85uint8(ptr %this, i8 %r, i8 %g, i8 %b) {
  %r1 = alloca i8, align 1
  %g2 = alloca i8, align 1
  %b3 = alloca i8, align 1
  store i8 %r, ptr %r1, align 1
  store i8 %g, ptr %g2, align 1
  store i8 %b, ptr %b3, align 1
  %r4 = getelementptr inbounds %Color, ptr %this, i32 0, i32 0
  %r.load = load i8, ptr %r1, align 1
  store i8 %r.load, ptr %r4, align 1
  %g5 = getelementptr inbounds %Color, ptr %this, i32 0, i32 1
  %g.load = load i8, ptr %g2, align 1
  store i8 %g.load, ptr %g5, align 1
  %b6 = getelementptr inbounds %Color, ptr %this, i32 0, i32 2
  %b.load = load i8, ptr %b3, align 1
  store i8 %b.load, ptr %b6, align 1
  ret void
}

define void @_EN36constructor-autogenerated-c-import_h9Rectangle4initE5float5float5float5float(ptr %this, float %x, float %y, float %width, float %height) {
  %x1 = alloca float, align 4
  %y2 = alloca float, align 4
  %width3 = alloca float, align 4
  %height4 = alloca float, align 4
  store float %x, ptr %x1, align 4
  store float %y, ptr %y2, align 4
  store float %width, ptr %width3, align 4
  store float %height, ptr %height4, align 4
  %x5 = getelementptr inbounds %Rectangle, ptr %this, i32 0, i32 0
  %x.load = load float, ptr %x1, align 4
  store float %x.load, ptr %x5, align 4
  %y6 = getelementptr inbounds %Rectangle, ptr %this, i32 0, i32 1
  %y.load = load float, ptr %y2, align 4
  store float %y.load, ptr %y6, align 4
  %width7 = getelementptr inbounds %Rectangle, ptr %this, i32 0, i32 2
  %width.load = load float, ptr %width3, align 4
  store float %width.load, ptr %width7, align 4
  %height8 = getelementptr inbounds %Rectangle, ptr %this, i32 0, i32 3
  %height.load = load float, ptr %height4, align 4
  store float %height.load, ptr %height8, align 4
  ret void
}
