// Fixture for wasm/test-wasi-shim.mjs and wasm/test-pipeline.mjs: example C
// code as generated by `cx --print-c --backend=c --c-dispatch` for a small cx
// program printing "45\n6765\n25\n120\n". Regenerate after C backend
// changes with:
//   ./build/cx --print-c --backend=c --c-dispatch <program.cx> > wasm/fixtures/smoke.c
// (then re-add this header).
#include <stdio.h>
#include <stdint.h>
#include <stdlib.h>
#include <string.h>
#include <stdbool.h>
#ifdef __wasm
// xcc's WebAssembly libc neither declares nor defines abort(), so map
// it to exit() (which terminates the process via WASI). Other
// toolchains are unaffected by this fallback.
static void cx_wasm_abort(void) {
    exit(1);
}
#define abort cx_wasm_abort
// The glibc-specific backtrace API is unavailable to WebAssembly
// toolchains, so provide no-op stubs (stack traces are simply empty).
int backtrace(void** array, int size) {
    (void)array;
    (void)size;
    return 0;
}
char** backtrace_symbols(void** array, int size) {
    (void)array;
    (void)size;
    return 0;
}
#endif

struct _4FILE {
    char _cx_empty;
};

struct _16OutputFileStream {
    struct _4FILE* file;
};

struct _4ListI4charE {
    char* buffer;
    int size;
    int capacity;
};

struct _12StringBuffer {
    struct _4ListI4charE characters;
};

struct _8ArrayRefI4charE {
    char* data;
    int size;
};

struct _6string {
    struct _8ArrayRefI4charE characters;
};

struct _14StringIterator {
    char* current;
    char* end;
};

struct _13RangeIteratorI3intE {
    int current;
    int end;
};

struct _5RangeI3intE {
    int start;
    int end;
};

struct _13ArrayIteratorI4charE {
    char* current;
    char* end;
};

struct _5Point {
    int x;
    int y;
};

struct _13ArrayIteratorI3intE {
    int* current;
    int* end;
};

// Module 'std' forward declarations
struct _16OutputFileStream _EN3std6stdoutE(void);
void _EN3std16OutputFileStream4initE14fileDescriptor3int(struct _16OutputFileStream* this, int fileDescriptor);
struct _16OutputFileStream _EN3std6stderrE(void);
int _EN3std11convertHashE6uint64(uint64_t hash);
struct _12StringBuffer _EN3stdplE6string6string(struct _6string a, struct _6string b);
void _EN3std12StringBuffer6deinitE(struct _12StringBuffer* this);
void _EN3std12StringBuffer4initE(struct _12StringBuffer* this);
struct _14StringIterator _EN3std6string8iteratorE(struct _6string* this);
_Bool _EN3std14StringIterator8hasValueE(struct _14StringIterator* this);
char _EN3std14StringIterator5valueE(struct _14StringIterator* this);
void _EN3std12StringBuffer4pushE4char(struct _12StringBuffer* this, char c);
void _EN3std14StringIterator9incrementE(struct _14StringIterator* this);
struct _12StringBuffer _EN3stdplE6string4char(struct _6string a, char b);
void _EN3std6string4initEP4char3int(struct _6string* this, char* pointer, int length);
struct _12StringBuffer _EN3stdplE6stringAU_4char(struct _6string a, char* b);
void _EN3std6string4initEP4char(struct _6string* this, char* cString);
struct _12StringBuffer _EN3stdplE12StringBuffer6string(struct _12StringBuffer a, struct _6string b);
struct _12StringBuffer _EN3stdplE12StringBuffer4char(struct _12StringBuffer a, char b);
struct _12StringBuffer _EN3stdplE12StringBufferAU_4char(struct _12StringBuffer a, char* b);
_Bool _EN3stdeqEP12StringBufferP12StringBuffer(struct _12StringBuffer* a, struct _12StringBuffer* b);
_Bool _EN3stdeqE6string6string(struct _6string a, struct _6string b);
void _EN3std6string4initEP12StringBuffer(struct _6string* this, struct _12StringBuffer* stringBuffer);
_Bool _EN3stdeqEP12StringBuffer6string(struct _12StringBuffer* a, struct _6string b);
_Bool _EN3stdneEP12StringBuffer6string(struct _12StringBuffer* a, struct _6string b);
_Bool _EN3stdneI6stringEEP6stringP6string(struct _6string* a, struct _6string* b);
_Bool _EN3stdeqE6stringP12StringBuffer(struct _6string a, struct _12StringBuffer* b);
_Bool _EN3stdneE6stringP12StringBuffer(struct _6string a, struct _12StringBuffer* b);
_Bool _EN3stdeqEAU_4charP12StringBuffer(char* a, struct _12StringBuffer* b);
_Bool _EN3stdneEAU_4charP12StringBuffer(char* a, struct _12StringBuffer* b);
_Bool _EN3stdeqEP12StringBufferAU_4char(struct _12StringBuffer* a, char* b);
_Bool _EN3stdneEP12StringBufferAU_4char(struct _12StringBuffer* a, char* b);
void _EN3std12abortWrapperE(void);
void _EN3std15printStackTraceE(void);
void _EN3std16setAbortBehaviorE(void);
void _EN3std10printFloatE7float64P12StringBuffer(double value, struct _12StringBuffer* stream);
_Bool _EN3std12StringBuffer5writeE6string(struct _12StringBuffer* this, struct _6string s);
void _EN3std11printSignedE5int64P12StringBuffer(int64_t value, struct _12StringBuffer* stream);
void _EN3std13printUnsignedE6uint64P12StringBuffer(uint64_t value, struct _12StringBuffer* stream);
int backtrace(void** array, int size);
char** backtrace_symbols(void** array, int size);
struct _13RangeIteratorI3intE _EN3std5RangeI3intE8iteratorE(struct _5RangeI3intE* this);
void _EN3std5RangeI3intE4initE3int3int(struct _5RangeI3intE* this, int start, int end);
_Bool _EN3std13RangeIteratorI3intE8hasValueE(struct _13RangeIteratorI3intE* this);
int _EN3std13RangeIteratorI3intE5valueE(struct _13RangeIteratorI3intE* this);
void _EN3std13RangeIteratorI3intE9incrementE(struct _13RangeIteratorI3intE* this);
void _EN3std7printlnEOAU_4char(char const* value);
void _EN3std5printEOAU_4char(char const* cString);
void _EN3std5printI4charEE4char(char value);
struct _12StringBuffer _EN3std8readLineE(void);
struct _12StringBuffer _EN3std8readFileE6string(struct _6string path);
char* _EN3std12StringBuffer7cStringE(struct _12StringBuffer* this);
void _EN3std12StringBuffer4initE6string(struct _12StringBuffer* this, struct _6string s);
void _EN3std10assertFailEP4char(char const* message);
void _EN3std12StringBuffer4initE17uninitializedSize3int(struct _12StringBuffer* this, int uninitializedSize);
char* _EN3std12StringBuffer4dataE(struct _12StringBuffer* this);
_Bool _EN3std9writeFileE6string6string(struct _6string path, struct _6string content);
char* _EN3std6string4dataE(struct _6string* this);
int _EN3std6string4sizeE(struct _6string* this);
char _EN3std6stringixE3int(struct _6string* this, int index);
_Bool _EN3stdeqEP4char6string(char* a, struct _6string b);
_Bool _EN3stdneEP4char6string(char* a, struct _6string b);
_Bool _EN3stdeqE6stringP4char(struct _6string a, char* b);
_Bool _EN3stdneE6stringP4char(struct _6string a, char* b);
void _EN3std7printlnI6string3int6stringEEP6stringP3intP6string(struct _6string* _0, int* _1, struct _6string* _2);
void _EN3std4ListI4charE6deinitE(struct _4ListI4charE* this);
void _EN3std4ListI4charE4initE(struct _4ListI4charE* this);
void _EN3std4ListI4charE4pushE4char(struct _4ListI4charE* this, char element);
void _EN3std14StringIterator4initE6string(struct _14StringIterator* this, struct _6string s);
void _EN3std4ListI4charEixaE3int4char(struct _4ListI4charE* this, int index, char element);
int _EN3std12StringBuffer4sizeE(struct _12StringBuffer* this);
void _EN3std8ArrayRefI4charE4initEP4char3int(struct _8ArrayRefI4charE* this, char* data, int size);
int _EN3std6string7compareEP6string(struct _6string* this, struct _6string* other);
void _EN3std13RangeIteratorI3intE4initE5RangeI3intE(struct _13RangeIteratorI3intE* this, struct _5RangeI3intE range);
struct _12StringBuffer _EN3std4char8toStringE(char* this);
void _EN3std4ListI4charE4initE8capacity3int(struct _4ListI4charE* this, int capacity);
void _EN3std4ListI4charE4initE17uninitializedSize3int(struct _4ListI4charE* this, int uninitializedSize);
char* _EN3std4ListI4charE4dataE(struct _4ListI4charE* this);
char* _EN3std8ArrayRefI4charE4dataE(struct _8ArrayRefI4charE* this);
int _EN3std8ArrayRefI4charE4sizeE(struct _8ArrayRefI4charE* this);
char* _EN3std8ArrayRefI4charEixE3int(struct _8ArrayRefI4charE* this, int index);
void _EN3std5printI6stringEEP6string(struct _6string* value);
void _EN3std5printI3intEEP3int(int* value);
struct _13ArrayIteratorI4charE _EN3std4ListI4charE8iteratorE(struct _4ListI4charE* this);
_Bool _EN3std13ArrayIteratorI4charE8hasValueE(struct _13ArrayIteratorI4charE* this);
char* _EN3std13ArrayIteratorI4charE5valueE(struct _13ArrayIteratorI4charE* this);
void _EN3std13ArrayIteratorI4charE9incrementE(struct _13ArrayIteratorI4charE* this);
void _EN3std10deallocateIAU_4charEEAU_4char(char* allocation);
void _EN3std4ListI4charE4growE(struct _4ListI4charE* this);
int _EN3std4ListI4charE4sizeE(struct _4ListI4charE* this);
int* _EN3std3minI3intEEP3intP3int(int* a, int* b);
int _EN3std5RangeI3intE5startE(struct _5RangeI3intE* this);
int _EN3std5RangeI3intE3endE(struct _5RangeI3intE* this);
void _EN3std4char5printEP12StringBuffer(char* this, struct _12StringBuffer* stream);
void _EN3std4ListI4charE7reserveE3int(struct _4ListI4charE* this, int minimumCapacity);
char* _EN3std13allocateArrayI4charEE3int(int size);
void _EN3std8ArrayRefI4charE16indexOutOfBoundsE6string3int(struct _8ArrayRefI4charE* this, struct _6string function, int index);
struct _12StringBuffer _EN3std6string8toStringE(struct _6string* this);
struct _12StringBuffer _EN3std3int8toStringE(int* this);
void _EN3std13ArrayIteratorI4charE4initE8ArrayRefI4charE(struct _13ArrayIteratorI4charE* this, struct _8ArrayRefI4charE array);
void _EN3std8ArrayRefI4charE4initEP4ListI4charE(struct _8ArrayRefI4charE* this, struct _4ListI4charE* list);
void _EN3std5abortI6string6string6string3int6string3intEEP6stringP6stringP6stringP3intP6stringP3int(struct _6string* _0, struct _6string* _1, struct _6string* _2, int* _3, struct _6string* _4, int* _5);
void _EN3std6string5printEP12StringBuffer(struct _6string* this, struct _12StringBuffer* stream);
void _EN3std3int5printEP12StringBuffer(int* this, struct _12StringBuffer* stream);
void _EN3std16OutputFileStream5writeI6stringEEP6string(struct _16OutputFileStream* this, struct _6string* value);
void _EN3std16OutputFileStream5writeI3intEEP3int(struct _16OutputFileStream* this, int* value);
void _EN3std16OutputFileStream5writeI4charEEP4char(struct _16OutputFileStream* this, char* value);

// Module 'std' definitions

struct _16OutputFileStream _EN3std6stdoutE(void) {
    struct _16OutputFileStream _alloca0;
    struct _16OutputFileStream _load1;
    int _cx_pc = 0;
    while (1) {
        switch (_cx_pc) {
        case 0: {
    _EN3std16OutputFileStream4initE14fileDescriptor3int((&_alloca0), 1);
    _load1 = *(&_alloca0);
    return _load1;
        }
        default: abort();
        }
    }
}

void _EN3std16OutputFileStream4initE14fileDescriptor3int(struct _16OutputFileStream* this, int fileDescriptor) {
    struct _6string __str0;
    int _alloca1;
    struct _6string __str2;
    struct _4FILE** _const_get_element_ptr3;
    struct _4FILE* _call4;
    struct _4FILE** _const_get_element_ptr5;
    struct _4FILE* _load6;
    _Bool _binary_op7;
    int _cx_pc = 0;
    while (1) {
        switch (_cx_pc) {
        case 0: {
    _const_get_element_ptr3 = &this->file;
    _call4 = fdopen(fileDescriptor, "w");
    *_const_get_element_ptr3 = _call4;
    _const_get_element_ptr5 = &this->file;
    _load6 = *_const_get_element_ptr5;
    _binary_op7 = _load6 == NULL;
    if (_binary_op7) {
        _cx_pc = 1;
    } else {
        _cx_pc = 2;
    }
    break;
        }
        case 1: {
    _EN3std6string4initEP4char3int((&__str0), "Couldn't open file descriptor ", 30);
    *(&_alloca1) = fileDescriptor;
    _EN3std6string4initEP4char3int((&__str2), " for writing", 12);
    _EN3std7printlnI6string3int6stringEEP6stringP3intP6string((&__str0), (&_alloca1), (&__str2));
    abort();
    _cx_pc = 3;
    break;
        }
        case 2: {
    _cx_pc = 3;
    break;
        }
        case 3: {
    return;
        }
        default: abort();
        }
    }
}

struct _16OutputFileStream _EN3std6stderrE(void) {
    struct _16OutputFileStream _alloca0;
    struct _16OutputFileStream _load1;
    int _cx_pc = 0;
    while (1) {
        switch (_cx_pc) {
        case 0: {
    _EN3std16OutputFileStream4initE14fileDescriptor3int((&_alloca0), 2);
    _load1 = *(&_alloca0);
    return _load1;
        }
        default: abort();
        }
    }
}

int _EN3std11convertHashE6uint64(uint64_t hash) {
    int _cast0;
    int _binary_op1;
    int _cx_pc = 0;
    while (1) {
        switch (_cx_pc) {
        case 0: {
    _cast0 = (int) hash;
    _binary_op1 = _cast0 & 2147483647;
    return _binary_op1;
        }
        default: abort();
        }
    }
}

struct _12StringBuffer _EN3stdplE6string6string(struct _6string a, struct _6string b) {
    struct _12StringBuffer result0;
    struct _14StringIterator __iterator1;
    struct _6string _alloca2;
    char ch3;
    struct _14StringIterator __iterator4;
    struct _6string _alloca5;
    char ch6;
    struct _14StringIterator _call7;
    _Bool _call8;
    char _call9;
    char _load10;
    struct _14StringIterator _call11;
    _Bool _call12;
    char _call13;
    char _load14;
    struct _12StringBuffer _load15;
    int _cx_pc = 0;
    while (1) {
        switch (_cx_pc) {
        case 0: {
    _EN3std12StringBuffer4initE((&result0));
    *(&_alloca2) = a;
    _call7 = _EN3std6string8iteratorE((&_alloca2));
    *(&__iterator1) = _call7;
    _cx_pc = 1;
    break;
        }
        case 1: {
    _call8 = _EN3std14StringIterator8hasValueE((&__iterator1));
    if (_call8) {
        _cx_pc = 2;
    } else {
        _cx_pc = 4;
    }
    break;
        }
        case 2: {
    _call9 = _EN3std14StringIterator5valueE((&__iterator1));
    *(&ch3) = _call9;
    _load10 = *(&ch3);
    _EN3std12StringBuffer4pushE4char((&result0), _load10);
    _cx_pc = 3;
    break;
        }
        case 3: {
    _EN3std14StringIterator9incrementE((&__iterator1));
    _cx_pc = 1;
    break;
        }
        case 4: {
    *(&_alloca5) = b;
    _call11 = _EN3std6string8iteratorE((&_alloca5));
    *(&__iterator4) = _call11;
    _cx_pc = 5;
    break;
        }
        case 5: {
    _call12 = _EN3std14StringIterator8hasValueE((&__iterator4));
    if (_call12) {
        _cx_pc = 6;
    } else {
        _cx_pc = 8;
    }
    break;
        }
        case 6: {
    _call13 = _EN3std14StringIterator5valueE((&__iterator4));
    *(&ch6) = _call13;
    _load14 = *(&ch6);
    _EN3std12StringBuffer4pushE4char((&result0), _load14);
    _cx_pc = 7;
    break;
        }
        case 7: {
    _EN3std14StringIterator9incrementE((&__iterator4));
    _cx_pc = 5;
    break;
        }
        case 8: {
    _load15 = *(&result0);
    return _load15;
        }
        default: abort();
        }
    }
}

void _EN3std12StringBuffer6deinitE(struct _12StringBuffer* this) {
    struct _4ListI4charE* _const_get_element_ptr0;
    int _cx_pc = 0;
    while (1) {
        switch (_cx_pc) {
        case 0: {
    _const_get_element_ptr0 = &this->characters;
    _EN3std4ListI4charE6deinitE(_const_get_element_ptr0);
    return;
        }
        default: abort();
        }
    }
}

void _EN3std12StringBuffer4initE(struct _12StringBuffer* this) {
    struct _4ListI4charE _alloca0;
    struct _4ListI4charE* _const_get_element_ptr1;
    struct _4ListI4charE _load2;
    struct _4ListI4charE* _const_get_element_ptr3;
    int _cx_pc = 0;
    while (1) {
        switch (_cx_pc) {
        case 0: {
    _const_get_element_ptr1 = &this->characters;
    _EN3std4ListI4charE4initE((&_alloca0));
    _load2 = *(&_alloca0);
    *_const_get_element_ptr1 = _load2;
    _const_get_element_ptr3 = &this->characters;
    _EN3std4ListI4charE4pushE4char(_const_get_element_ptr3, 0);
    return;
        }
        default: abort();
        }
    }
}

struct _14StringIterator _EN3std6string8iteratorE(struct _6string* this) {
    struct _14StringIterator _alloca0;
    struct _6string _load1;
    struct _14StringIterator _load2;
    int _cx_pc = 0;
    while (1) {
        switch (_cx_pc) {
        case 0: {
    _load1 = *this;
    _EN3std14StringIterator4initE6string((&_alloca0), _load1);
    _load2 = *(&_alloca0);
    return _load2;
        }
        default: abort();
        }
    }
}

_Bool _EN3std14StringIterator8hasValueE(struct _14StringIterator* this) {
    char** _const_get_element_ptr0;
    char* _load1;
    char** _const_get_element_ptr2;
    char* _load3;
    _Bool _binary_op4;
    int _cx_pc = 0;
    while (1) {
        switch (_cx_pc) {
        case 0: {
    _const_get_element_ptr0 = &this->current;
    _load1 = *_const_get_element_ptr0;
    _const_get_element_ptr2 = &this->end;
    _load3 = *_const_get_element_ptr2;
    _binary_op4 = _load1 != _load3;
    return _binary_op4;
        }
        default: abort();
        }
    }
}

char _EN3std14StringIterator5valueE(struct _14StringIterator* this) {
    char** _const_get_element_ptr0;
    char* _load1;
    char _load2;
    int _cx_pc = 0;
    while (1) {
        switch (_cx_pc) {
        case 0: {
    _const_get_element_ptr0 = &this->current;
    _load1 = *_const_get_element_ptr0;
    _load2 = *_load1;
    return _load2;
        }
        default: abort();
        }
    }
}

void _EN3std12StringBuffer4pushE4char(struct _12StringBuffer* this, char c) {
    struct _4ListI4charE* _const_get_element_ptr0;
    int _call1;
    struct _4ListI4charE* _const_get_element_ptr2;
    int _cx_pc = 0;
    while (1) {
        switch (_cx_pc) {
        case 0: {
    _const_get_element_ptr0 = &this->characters;
    _call1 = _EN3std12StringBuffer4sizeE(this);
    _EN3std4ListI4charEixaE3int4char(_const_get_element_ptr0, _call1, c);
    _const_get_element_ptr2 = &this->characters;
    _EN3std4ListI4charE4pushE4char(_const_get_element_ptr2, 0);
    return;
        }
        default: abort();
        }
    }
}

void _EN3std14StringIterator9incrementE(struct _14StringIterator* this) {
    char** _const_get_element_ptr0;
    char* _load1;
    char* _get_element_ptr2;
    int _cx_pc = 0;
    while (1) {
        switch (_cx_pc) {
        case 0: {
    _const_get_element_ptr0 = &this->current;
    _load1 = *_const_get_element_ptr0;
    _get_element_ptr2 = &(_load1[1]);
    *_const_get_element_ptr0 = _get_element_ptr2;
    return;
        }
        default: abort();
        }
    }
}

struct _12StringBuffer _EN3stdplE6string4char(struct _6string a, char b) {
    struct _6string _alloca0;
    char _alloca1;
    struct _6string _load2;
    struct _12StringBuffer _call3;
    int _cx_pc = 0;
    while (1) {
        switch (_cx_pc) {
        case 0: {
    *(&_alloca1) = b;
    _EN3std6string4initEP4char3int((&_alloca0), (&_alloca1), 1);
    _load2 = *(&_alloca0);
    _call3 = _EN3stdplE6string6string(a, _load2);
    return _call3;
        }
        default: abort();
        }
    }
}

void _EN3std6string4initEP4char3int(struct _6string* this, char* pointer, int length) {
    struct _8ArrayRefI4charE _alloca0;
    struct _8ArrayRefI4charE* _const_get_element_ptr1;
    struct _8ArrayRefI4charE _load2;
    int _cx_pc = 0;
    while (1) {
        switch (_cx_pc) {
        case 0: {
    _const_get_element_ptr1 = &this->characters;
    _EN3std8ArrayRefI4charE4initEP4char3int((&_alloca0), pointer, length);
    _load2 = *(&_alloca0);
    *_const_get_element_ptr1 = _load2;
    return;
        }
        default: abort();
        }
    }
}

struct _12StringBuffer _EN3stdplE6stringAU_4char(struct _6string a, char* b) {
    struct _6string _alloca0;
    struct _6string _load1;
    struct _12StringBuffer _call2;
    int _cx_pc = 0;
    while (1) {
        switch (_cx_pc) {
        case 0: {
    _EN3std6string4initEP4char((&_alloca0), b);
    _load1 = *(&_alloca0);
    _call2 = _EN3stdplE6string6string(a, _load1);
    return _call2;
        }
        default: abort();
        }
    }
}

void _EN3std6string4initEP4char(struct _6string* this, char* cString) {
    struct _8ArrayRefI4charE _alloca0;
    struct _8ArrayRefI4charE* _const_get_element_ptr1;
    uint64_t _call2;
    int _cast3;
    struct _8ArrayRefI4charE _load4;
    int _cx_pc = 0;
    while (1) {
        switch (_cx_pc) {
        case 0: {
    _const_get_element_ptr1 = &this->characters;
    _call2 = strlen(cString);
    _cast3 = (int) _call2;
    _EN3std8ArrayRefI4charE4initEP4char3int((&_alloca0), cString, _cast3);
    _load4 = *(&_alloca0);
    *_const_get_element_ptr1 = _load4;
    return;
        }
        default: abort();
        }
    }
}

struct _12StringBuffer _EN3stdplE12StringBuffer6string(struct _12StringBuffer a, struct _6string b) {
    struct _12StringBuffer result0;
    struct _14StringIterator __iterator1;
    struct _6string _alloca2;
    char ch3;
    struct _14StringIterator _call4;
    _Bool _call5;
    char _call6;
    char _load7;
    struct _12StringBuffer _load8;
    int _cx_pc = 0;
    while (1) {
        switch (_cx_pc) {
        case 0: {
    *(&result0) = a;
    *(&_alloca2) = b;
    _call4 = _EN3std6string8iteratorE((&_alloca2));
    *(&__iterator1) = _call4;
    _cx_pc = 1;
    break;
        }
        case 1: {
    _call5 = _EN3std14StringIterator8hasValueE((&__iterator1));
    if (_call5) {
        _cx_pc = 2;
    } else {
        _cx_pc = 4;
    }
    break;
        }
        case 2: {
    _call6 = _EN3std14StringIterator5valueE((&__iterator1));
    *(&ch3) = _call6;
    _load7 = *(&ch3);
    _EN3std12StringBuffer4pushE4char((&result0), _load7);
    _cx_pc = 3;
    break;
        }
        case 3: {
    _EN3std14StringIterator9incrementE((&__iterator1));
    _cx_pc = 1;
    break;
        }
        case 4: {
    _load8 = *(&result0);
    return _load8;
        }
        default: abort();
        }
    }
}

struct _12StringBuffer _EN3stdplE12StringBuffer4char(struct _12StringBuffer a, char b) {
    struct _12StringBuffer result0;
    struct _12StringBuffer _load1;
    int _cx_pc = 0;
    while (1) {
        switch (_cx_pc) {
        case 0: {
    *(&result0) = a;
    _EN3std12StringBuffer4pushE4char((&result0), b);
    _load1 = *(&result0);
    return _load1;
        }
        default: abort();
        }
    }
}

struct _12StringBuffer _EN3stdplE12StringBufferAU_4char(struct _12StringBuffer a, char* b) {
    struct _6string _alloca0;
    struct _6string _load1;
    struct _12StringBuffer _call2;
    int _cx_pc = 0;
    while (1) {
        switch (_cx_pc) {
        case 0: {
    _EN3std6string4initEP4char((&_alloca0), b);
    _load1 = *(&_alloca0);
    _call2 = _EN3stdplE12StringBuffer6string(a, _load1);
    return _call2;
        }
        default: abort();
        }
    }
}

_Bool _EN3stdeqEP12StringBufferP12StringBuffer(struct _12StringBuffer* a, struct _12StringBuffer* b) {
    struct _6string _alloca0;
    struct _6string _alloca1;
    struct _6string _load2;
    struct _6string _load3;
    _Bool _call4;
    int _cx_pc = 0;
    while (1) {
        switch (_cx_pc) {
        case 0: {
    _EN3std6string4initEP12StringBuffer((&_alloca0), a);
    _load2 = *(&_alloca0);
    _EN3std6string4initEP12StringBuffer((&_alloca1), b);
    _load3 = *(&_alloca1);
    _call4 = _EN3stdeqE6string6string(_load2, _load3);
    return _call4;
        }
        default: abort();
        }
    }
}

_Bool _EN3stdeqE6string6string(struct _6string a, struct _6string b) {
    struct _6string _alloca0;
    struct _6string _alloca1;
    struct _13RangeIteratorI3intE __iterator2;
    struct _5RangeI3intE _alloca3;
    struct _6string _alloca4;
    int index5;
    struct _6string _alloca6;
    struct _6string _alloca7;
    int _call8;
    int _call9;
    _Bool _binary_op10;
    int _call11;
    struct _13RangeIteratorI3intE _call12;
    _Bool _call13;
    int _call14;
    int _load15;
    char _call16;
    int _load17;
    char _call18;
    _Bool _binary_op19;
    int _cx_pc = 0;
    while (1) {
        switch (_cx_pc) {
        case 0: {
    *(&_alloca0) = a;
    _call8 = _EN3std6string4sizeE((&_alloca0));
    *(&_alloca1) = b;
    _call9 = _EN3std6string4sizeE((&_alloca1));
    _binary_op10 = _call8 != _call9;
    if (_binary_op10) {
        _cx_pc = 1;
    } else {
        _cx_pc = 2;
    }
    break;
        }
        case 1: {
    return false;
        }
        case 2: {
    _cx_pc = 3;
    break;
        }
        case 3: {
    *(&_alloca4) = a;
    _call11 = _EN3std6string4sizeE((&_alloca4));
    _EN3std5RangeI3intE4initE3int3int((&_alloca3), 0, _call11);
    _call12 = _EN3std5RangeI3intE8iteratorE((&_alloca3));
    *(&__iterator2) = _call12;
    _cx_pc = 4;
    break;
        }
        case 4: {
    _call13 = _EN3std13RangeIteratorI3intE8hasValueE((&__iterator2));
    if (_call13) {
        _cx_pc = 5;
    } else {
        _cx_pc = 7;
    }
    break;
        }
        case 5: {
    _call14 = _EN3std13RangeIteratorI3intE5valueE((&__iterator2));
    *(&index5) = _call14;
    *(&_alloca6) = a;
    _load15 = *(&index5);
    _call16 = _EN3std6stringixE3int((&_alloca6), _load15);
    *(&_alloca7) = b;
    _load17 = *(&index5);
    _call18 = _EN3std6stringixE3int((&_alloca7), _load17);
    _binary_op19 = _call16 != _call18;
    if (_binary_op19) {
        _cx_pc = 8;
    } else {
        _cx_pc = 9;
    }
    break;
        }
        case 6: {
    _EN3std13RangeIteratorI3intE9incrementE((&__iterator2));
    _cx_pc = 4;
    break;
        }
        case 7: {
    return true;
        }
        case 8: {
    return false;
        }
        case 9: {
    _cx_pc = 10;
    break;
        }
        case 10: {
    _cx_pc = 6;
    break;
        }
        default: abort();
        }
    }
}

void _EN3std6string4initEP12StringBuffer(struct _6string* this, struct _12StringBuffer* stringBuffer) {
    struct _8ArrayRefI4charE _alloca0;
    struct _8ArrayRefI4charE* _const_get_element_ptr1;
    char* _call2;
    int _call3;
    struct _8ArrayRefI4charE _load4;
    int _cx_pc = 0;
    while (1) {
        switch (_cx_pc) {
        case 0: {
    _const_get_element_ptr1 = &this->characters;
    _call2 = _EN3std12StringBuffer4dataE(stringBuffer);
    _call3 = _EN3std12StringBuffer4sizeE(stringBuffer);
    _EN3std8ArrayRefI4charE4initEP4char3int((&_alloca0), _call2, _call3);
    _load4 = *(&_alloca0);
    *_const_get_element_ptr1 = _load4;
    return;
        }
        default: abort();
        }
    }
}

_Bool _EN3stdeqEP12StringBuffer6string(struct _12StringBuffer* a, struct _6string b) {
    struct _6string _alloca0;
    struct _6string _load1;
    _Bool _call2;
    int _cx_pc = 0;
    while (1) {
        switch (_cx_pc) {
        case 0: {
    _EN3std6string4initEP12StringBuffer((&_alloca0), a);
    _load1 = *(&_alloca0);
    _call2 = _EN3stdeqE6string6string(_load1, b);
    return _call2;
        }
        default: abort();
        }
    }
}

_Bool _EN3stdneEP12StringBuffer6string(struct _12StringBuffer* a, struct _6string b) {
    struct _6string _alloca0;
    struct _6string _alloca1;
    _Bool _call2;
    int _cx_pc = 0;
    while (1) {
        switch (_cx_pc) {
        case 0: {
    _EN3std6string4initEP12StringBuffer((&_alloca0), a);
    *(&_alloca1) = b;
    _call2 = _EN3stdneI6stringEEP6stringP6string((&_alloca0), (&_alloca1));
    return _call2;
        }
        default: abort();
        }
    }
}

_Bool _EN3stdneI6stringEEP6stringP6string(struct _6string* a, struct _6string* b) {
    int _call0;
    _Bool _binary_op1;
    int _cx_pc = 0;
    while (1) {
        switch (_cx_pc) {
        case 0: {
    _call0 = _EN3std6string7compareEP6string(a, b);
    _binary_op1 = _call0 != 1;
    return _binary_op1;
        }
        default: abort();
        }
    }
}

_Bool _EN3stdeqE6stringP12StringBuffer(struct _6string a, struct _12StringBuffer* b) {
    struct _6string _alloca0;
    struct _6string _load1;
    _Bool _call2;
    int _cx_pc = 0;
    while (1) {
        switch (_cx_pc) {
        case 0: {
    _EN3std6string4initEP12StringBuffer((&_alloca0), b);
    _load1 = *(&_alloca0);
    _call2 = _EN3stdeqE6string6string(a, _load1);
    return _call2;
        }
        default: abort();
        }
    }
}

_Bool _EN3stdneE6stringP12StringBuffer(struct _6string a, struct _12StringBuffer* b) {
    struct _6string _alloca0;
    struct _6string _alloca1;
    _Bool _call2;
    int _cx_pc = 0;
    while (1) {
        switch (_cx_pc) {
        case 0: {
    *(&_alloca0) = a;
    _EN3std6string4initEP12StringBuffer((&_alloca1), b);
    _call2 = _EN3stdneI6stringEEP6stringP6string((&_alloca0), (&_alloca1));
    return _call2;
        }
        default: abort();
        }
    }
}

_Bool _EN3stdeqEAU_4charP12StringBuffer(char* a, struct _12StringBuffer* b) {
    struct _6string _alloca0;
    struct _6string _alloca1;
    struct _6string _load2;
    struct _6string _load3;
    _Bool _call4;
    int _cx_pc = 0;
    while (1) {
        switch (_cx_pc) {
        case 0: {
    _EN3std6string4initEP4char((&_alloca0), a);
    _load2 = *(&_alloca0);
    _EN3std6string4initEP12StringBuffer((&_alloca1), b);
    _load3 = *(&_alloca1);
    _call4 = _EN3stdeqE6string6string(_load2, _load3);
    return _call4;
        }
        default: abort();
        }
    }
}

_Bool _EN3stdneEAU_4charP12StringBuffer(char* a, struct _12StringBuffer* b) {
    struct _6string _alloca0;
    struct _6string _alloca1;
    _Bool _call2;
    int _cx_pc = 0;
    while (1) {
        switch (_cx_pc) {
        case 0: {
    _EN3std6string4initEP4char((&_alloca0), a);
    _EN3std6string4initEP12StringBuffer((&_alloca1), b);
    _call2 = _EN3stdneI6stringEEP6stringP6string((&_alloca0), (&_alloca1));
    return _call2;
        }
        default: abort();
        }
    }
}

_Bool _EN3stdeqEP12StringBufferAU_4char(struct _12StringBuffer* a, char* b) {
    struct _6string _alloca0;
    struct _6string _alloca1;
    struct _6string _load2;
    struct _6string _load3;
    _Bool _call4;
    int _cx_pc = 0;
    while (1) {
        switch (_cx_pc) {
        case 0: {
    _EN3std6string4initEP12StringBuffer((&_alloca0), a);
    _load2 = *(&_alloca0);
    _EN3std6string4initEP4char((&_alloca1), b);
    _load3 = *(&_alloca1);
    _call4 = _EN3stdeqE6string6string(_load2, _load3);
    return _call4;
        }
        default: abort();
        }
    }
}

_Bool _EN3stdneEP12StringBufferAU_4char(struct _12StringBuffer* a, char* b) {
    struct _6string _alloca0;
    struct _6string _alloca1;
    _Bool _call2;
    int _cx_pc = 0;
    while (1) {
        switch (_cx_pc) {
        case 0: {
    _EN3std6string4initEP12StringBuffer((&_alloca0), a);
    _EN3std6string4initEP4char((&_alloca1), b);
    _call2 = _EN3stdneI6stringEEP6stringP6string((&_alloca0), (&_alloca1));
    return _call2;
        }
        default: abort();
        }
    }
}

void _EN3std12abortWrapperE(void) {
    int _cx_pc = 0;
    while (1) {
        switch (_cx_pc) {
        case 0: {
    _EN3std15printStackTraceE();
    _EN3std16setAbortBehaviorE();
    abort();
    abort();
        }
        default: abort();
        }
    }
}

void _EN3std15printStackTraceE(void) {
    void* callstack0[128];
    int frames1;
    char** strings2;
    struct _13RangeIteratorI3intE __iterator3;
    struct _5RangeI3intE _alloca4;
    int i5;
    void** _get_element_ptr6;
    int _call7;
    void** _get_element_ptr8;
    int _load9;
    char** _call10;
    char** _load11;
    _Bool _binary_op12;
    int _load13;
    struct _13RangeIteratorI3intE _call14;
    _Bool _call15;
    int _call16;
    char** _load17;
    int _load18;
    char** _get_element_ptr19;
    char* _load20;
    int _call21;
    char** _load22;
    void* _cast23;
    int _cx_pc = 0;
    while (1) {
        switch (_cx_pc) {
        case 0: {
    _get_element_ptr6 = &((&callstack0)[0][0]);
    _call7 = backtrace(_get_element_ptr6, 128);
    *(&frames1) = _call7;
    _get_element_ptr8 = &((&callstack0)[0][0]);
    _load9 = *(&frames1);
    _call10 = backtrace_symbols(_get_element_ptr8, _load9);
    *(&strings2) = _call10;
    _load11 = *(&strings2);
    _binary_op12 = _load11 == NULL;
    if (_binary_op12) {
        _cx_pc = 1;
    } else {
        _cx_pc = 2;
    }
    break;
        }
        case 1: {
    return;
        }
        case 2: {
    _cx_pc = 3;
    break;
        }
        case 3: {
    _load13 = *(&frames1);
    _EN3std5RangeI3intE4initE3int3int((&_alloca4), 0, _load13);
    _call14 = _EN3std5RangeI3intE8iteratorE((&_alloca4));
    *(&__iterator3) = _call14;
    _cx_pc = 4;
    break;
        }
        case 4: {
    _call15 = _EN3std13RangeIteratorI3intE8hasValueE((&__iterator3));
    if (_call15) {
        _cx_pc = 5;
    } else {
        _cx_pc = 7;
    }
    break;
        }
        case 5: {
    _call16 = _EN3std13RangeIteratorI3intE5valueE((&__iterator3));
    *(&i5) = _call16;
    _load17 = *(&strings2);
    _load18 = *(&i5);
    _get_element_ptr19 = &(_load17[_load18]);
    _load20 = *_get_element_ptr19;
    _call21 = printf("%s\n", _load20);
    _cx_pc = 6;
    break;
        }
        case 6: {
    _EN3std13RangeIteratorI3intE9incrementE((&__iterator3));
    _cx_pc = 4;
    break;
        }
        case 7: {
    _load22 = *(&strings2);
    _cast23 = (void*) _load22;
    free(_cast23);
    return;
        }
        default: abort();
        }
    }
}

void _EN3std16setAbortBehaviorE(void) {
    int _cx_pc = 0;
    while (1) {
        switch (_cx_pc) {
        case 0: {
    return;
        }
        default: abort();
        }
    }
}

void _EN3std10printFloatE7float64P12StringBuffer(double value, struct _12StringBuffer* stream) {
    char result0[1080];
    struct _6string _alloca1;
    char* _cast2;
    int _call3;
    char* _cast4;
    struct _6string _load5;
    _Bool _call6;
    int _cx_pc = 0;
    while (1) {
        switch (_cx_pc) {
        case 0: {
    _cast2 = (char*) (&result0);
    _call3 = sprintf(_cast2, "%g", value);
    _cast4 = (char*) (&result0);
    _EN3std6string4initEP4char((&_alloca1), _cast4);
    _load5 = *(&_alloca1);
    _call6 = _EN3std12StringBuffer5writeE6string(stream, _load5);
    return;
        }
        default: abort();
        }
    }
}

_Bool _EN3std12StringBuffer5writeE6string(struct _12StringBuffer* this, struct _6string s) {
    struct _14StringIterator __iterator0;
    struct _6string _alloca1;
    char ch2;
    struct _14StringIterator _call3;
    _Bool _call4;
    char _call5;
    char _load6;
    int _cx_pc = 0;
    while (1) {
        switch (_cx_pc) {
        case 0: {
    *(&_alloca1) = s;
    _call3 = _EN3std6string8iteratorE((&_alloca1));
    *(&__iterator0) = _call3;
    _cx_pc = 1;
    break;
        }
        case 1: {
    _call4 = _EN3std14StringIterator8hasValueE((&__iterator0));
    if (_call4) {
        _cx_pc = 2;
    } else {
        _cx_pc = 4;
    }
    break;
        }
        case 2: {
    _call5 = _EN3std14StringIterator5valueE((&__iterator0));
    *(&ch2) = _call5;
    _load6 = *(&ch2);
    _EN3std12StringBuffer4pushE4char(this, _load6);
    _cx_pc = 3;
    break;
        }
        case 3: {
    _EN3std14StringIterator9incrementE((&__iterator0));
    _cx_pc = 1;
    break;
        }
        case 4: {
    return true;
        }
        default: abort();
        }
    }
}

void _EN3std11printSignedE5int64P12StringBuffer(int64_t value, struct _12StringBuffer* stream) {
    char result0[22];
    struct _6string _alloca1;
    char* _cast2;
    int _call3;
    char* _cast4;
    struct _6string _load5;
    _Bool _call6;
    int _cx_pc = 0;
    while (1) {
        switch (_cx_pc) {
        case 0: {
    _cast2 = (char*) (&result0);
    _call3 = sprintf(_cast2, "%lld", value);
    _cast4 = (char*) (&result0);
    _EN3std6string4initEP4char((&_alloca1), _cast4);
    _load5 = *(&_alloca1);
    _call6 = _EN3std12StringBuffer5writeE6string(stream, _load5);
    return;
        }
        default: abort();
        }
    }
}

void _EN3std13printUnsignedE6uint64P12StringBuffer(uint64_t value, struct _12StringBuffer* stream) {
    char result0[22];
    struct _6string _alloca1;
    char* _cast2;
    int _call3;
    char* _cast4;
    struct _6string _load5;
    _Bool _call6;
    int _cx_pc = 0;
    while (1) {
        switch (_cx_pc) {
        case 0: {
    _cast2 = (char*) (&result0);
    _call3 = sprintf(_cast2, "%llu", value);
    _cast4 = (char*) (&result0);
    _EN3std6string4initEP4char((&_alloca1), _cast4);
    _load5 = *(&_alloca1);
    _call6 = _EN3std12StringBuffer5writeE6string(stream, _load5);
    return;
        }
        default: abort();
        }
    }
}

struct _13RangeIteratorI3intE _EN3std5RangeI3intE8iteratorE(struct _5RangeI3intE* this) {
    struct _13RangeIteratorI3intE _alloca0;
    struct _5RangeI3intE _load1;
    struct _13RangeIteratorI3intE _load2;
    int _cx_pc = 0;
    while (1) {
        switch (_cx_pc) {
        case 0: {
    _load1 = *this;
    _EN3std13RangeIteratorI3intE4initE5RangeI3intE((&_alloca0), _load1);
    _load2 = *(&_alloca0);
    return _load2;
        }
        default: abort();
        }
    }
}

void _EN3std5RangeI3intE4initE3int3int(struct _5RangeI3intE* this, int start, int end) {
    int* _const_get_element_ptr0;
    int* _const_get_element_ptr1;
    int _cx_pc = 0;
    while (1) {
        switch (_cx_pc) {
        case 0: {
    _const_get_element_ptr0 = &this->start;
    *_const_get_element_ptr0 = start;
    _const_get_element_ptr1 = &this->end;
    *_const_get_element_ptr1 = end;
    return;
        }
        default: abort();
        }
    }
}

_Bool _EN3std13RangeIteratorI3intE8hasValueE(struct _13RangeIteratorI3intE* this) {
    int* _const_get_element_ptr0;
    int _load1;
    int* _const_get_element_ptr2;
    int _load3;
    _Bool _binary_op4;
    int _cx_pc = 0;
    while (1) {
        switch (_cx_pc) {
        case 0: {
    _const_get_element_ptr0 = &this->current;
    _load1 = *_const_get_element_ptr0;
    _const_get_element_ptr2 = &this->end;
    _load3 = *_const_get_element_ptr2;
    _binary_op4 = _load1 != _load3;
    return _binary_op4;
        }
        default: abort();
        }
    }
}

int _EN3std13RangeIteratorI3intE5valueE(struct _13RangeIteratorI3intE* this) {
    int* _const_get_element_ptr0;
    int _load1;
    int _cx_pc = 0;
    while (1) {
        switch (_cx_pc) {
        case 0: {
    _const_get_element_ptr0 = &this->current;
    _load1 = *_const_get_element_ptr0;
    return _load1;
        }
        default: abort();
        }
    }
}

void _EN3std13RangeIteratorI3intE9incrementE(struct _13RangeIteratorI3intE* this) {
    int* _const_get_element_ptr0;
    int _load1;
    int _binary_op2;
    int _cx_pc = 0;
    while (1) {
        switch (_cx_pc) {
        case 0: {
    _const_get_element_ptr0 = &this->current;
    _load1 = *_const_get_element_ptr0;
    _binary_op2 = _load1 + 1;
    *_const_get_element_ptr0 = _binary_op2;
    return;
        }
        default: abort();
        }
    }
}

void _EN3std7printlnEOAU_4char(char const* value) {
    int _cx_pc = 0;
    while (1) {
        switch (_cx_pc) {
        case 0: {
    _EN3std5printEOAU_4char(value);
    _EN3std5printI4charEE4char(10);
    return;
        }
        default: abort();
        }
    }
}

void _EN3std5printEOAU_4char(char const* cString) {
    _Bool _binary_op0;
    int _call1;
    int _call2;
    int _cx_pc = 0;
    while (1) {
        switch (_cx_pc) {
        case 0: {
    _binary_op0 = cString != NULL;
    if (_binary_op0) {
        _cx_pc = 1;
    } else {
        _cx_pc = 2;
    }
    break;
        }
        case 1: {
    _call1 = printf("%s", cString);
    _cx_pc = 3;
    break;
        }
        case 2: {
    _call2 = printf("null");
    _cx_pc = 3;
    break;
        }
        case 3: {
    return;
        }
        default: abort();
        }
    }
}

void _EN3std5printI4charEE4char(char value) {
    struct _12StringBuffer s0;
    char _alloca1;
    struct _12StringBuffer _call2;
    int _call3;
    char* _call4;
    int _call5;
    int _cx_pc = 0;
    while (1) {
        switch (_cx_pc) {
        case 0: {
    *(&_alloca1) = value;
    _call2 = _EN3std4char8toStringE((&_alloca1));
    *(&s0) = _call2;
    _call3 = _EN3std12StringBuffer4sizeE((&s0));
    _call4 = _EN3std12StringBuffer4dataE((&s0));
    _call5 = printf("%.*s", _call3, _call4);
    _EN3std12StringBuffer6deinitE((&s0));
    return;
        }
        default: abort();
        }
    }
}

struct _12StringBuffer _EN3std8readLineE(void) {
    _Bool _cxp_or;
    struct _12StringBuffer line0;
    int c1;
    int _call2;
    int _load3;
    _Bool _binary_op4;
    struct _12StringBuffer _load5;
    int _load6;
    _Bool _binary_op7;
    int _load8;
    char _cast9;
    int _cx_pc = 0;
    while (1) {
        switch (_cx_pc) {
        case 0: {
    _EN3std12StringBuffer4initE((&line0));
    _cx_pc = 1;
    break;
        }
        case 1: {
    if (true) {
        _cx_pc = 2;
    } else {
        _cx_pc = 3;
    }
    break;
        }
        case 2: {
    _call2 = getchar();
    *(&c1) = _call2;
    _load3 = *(&c1);
    _binary_op4 = _load3 == 10;
    if (_binary_op4) {
        _cxp_or = _binary_op4;
        _cx_pc = 5;
    } else {
        _cx_pc = 4;
    }
    break;
        }
        case 3: {
    _load5 = *(&line0);
    return _load5;
        }
        case 4: {
    _load6 = *(&c1);
    _binary_op7 = _load6 < 0;
    _cxp_or = _binary_op7; // branch argument
    _cx_pc = 5;
    break;
        }
        case 5: {
    if (_cxp_or) {
        _cx_pc = 6;
    } else {
        _cx_pc = 7;
    }
    break;
        }
        case 6: {
    _cx_pc = 3;
    break;
        }
        case 7: {
    _cx_pc = 8;
    break;
        }
        case 8: {
    _load8 = *(&c1);
    _cast9 = (char) _load8;
    _EN3std12StringBuffer4pushE4char((&line0), _cast9);
    _cx_pc = 1;
    break;
        }
        default: abort();
        }
    }
}

struct _12StringBuffer _EN3std8readFileE6string(struct _6string path) {
    struct _4FILE* file0;
    struct _12StringBuffer _alloca1;
    struct _12StringBuffer _alloca2;
    int64_t size3;
    struct _12StringBuffer content4;
    char* _call5;
    struct _4FILE* _call6;
    struct _4FILE* _load7;
    _Bool _binary_op8;
    struct _12StringBuffer _load9;
    struct _4FILE* _load10;
    _Bool _binary_op11;
    struct _4FILE* _load12;
    _Bool _binary_op13;
    int64_t _call14;
    struct _4FILE* _load15;
    _Bool _binary_op16;
    int64_t _load17;
    int _cast18;
    char* _call19;
    void* _cast20;
    int64_t _load21;
    uint64_t _cast22;
    struct _4FILE* _load23;
    _Bool _binary_op24;
    uint64_t _call25;
    struct _4FILE* _load26;
    _Bool _binary_op27;
    int _call28;
    struct _12StringBuffer _load29;
    int _cx_pc = 0;
    while (1) {
        switch (_cx_pc) {
        case 0: {
    _EN3std12StringBuffer4initE6string((&_alloca1), path);
    _call5 = _EN3std12StringBuffer7cStringE((&_alloca1));
    _call6 = fopen(_call5, "rb");
    *(&file0) = _call6;
    _load7 = *(&file0);
    _binary_op8 = _load7 == NULL;
    if (_binary_op8) {
        _cx_pc = 1;
    } else {
        _cx_pc = 2;
    }
    break;
        }
        case 1: {
    _EN3std12StringBuffer4initE((&_alloca2));
    _load9 = *(&_alloca2);
    return _load9;
        }
        case 2: {
    _cx_pc = 3;
    break;
        }
        case 3: {
    _load10 = *(&file0);
    _binary_op11 = _load10 == NULL;
    if (_binary_op11) {
        _cx_pc = 4;
    } else {
        _cx_pc = 5;
    }
    break;
        }
        case 4: {
    _EN3std10assertFailEP4char("Unwrap failed at stdio.cx:110:11\n");
    _cx_pc = 5;
    break;
        }
        case 5: {
    fseek(_load10, 0, 2);
    _load12 = *(&file0);
    _binary_op13 = _load12 == NULL;
    if (_binary_op13) {
        _cx_pc = 6;
    } else {
        _cx_pc = 7;
    }
    break;
        }
        case 6: {
    _EN3std10assertFailEP4char("Unwrap failed at stdio.cx:111:22\n");
    _cx_pc = 7;
    break;
        }
        case 7: {
    _call14 = ftell(_load12);
    *(&size3) = _call14;
    _load15 = *(&file0);
    _binary_op16 = _load15 == NULL;
    if (_binary_op16) {
        _cx_pc = 8;
    } else {
        _cx_pc = 9;
    }
    break;
        }
        case 8: {
    _EN3std10assertFailEP4char("Unwrap failed at stdio.cx:112:11\n");
    _cx_pc = 9;
    break;
        }
        case 9: {
    fseek(_load15, 0, 0);
    _load17 = *(&size3);
    _cast18 = (int) _load17;
    _EN3std12StringBuffer4initE17uninitializedSize3int((&content4), _cast18);
    _call19 = _EN3std12StringBuffer4dataE((&content4));
    _cast20 = (void*) _call19;
    _load21 = *(&size3);
    _cast22 = (uint64_t) _load21;
    _load23 = *(&file0);
    _binary_op24 = _load23 == NULL;
    if (_binary_op24) {
        _cx_pc = 10;
    } else {
        _cx_pc = 11;
    }
    break;
        }
        case 10: {
    _EN3std10assertFailEP4char("Unwrap failed at stdio.cx:115:55\n");
    _cx_pc = 11;
    break;
        }
        case 11: {
    _call25 = fread(_cast20, sizeof(char), _cast22, _load23);
    _load26 = *(&file0);
    _binary_op27 = _load26 == NULL;
    if (_binary_op27) {
        _cx_pc = 12;
    } else {
        _cx_pc = 13;
    }
    break;
        }
        case 12: {
    _EN3std10assertFailEP4char("Unwrap failed at stdio.cx:108:18\n");
    _cx_pc = 13;
    break;
        }
        case 13: {
    _call28 = fclose(_load26);
    _load29 = *(&content4);
    return _load29;
        }
        default: abort();
        }
    }
}

char* _EN3std12StringBuffer7cStringE(struct _12StringBuffer* this) {
    char* _call0;
    int _cx_pc = 0;
    while (1) {
        switch (_cx_pc) {
        case 0: {
    _call0 = _EN3std12StringBuffer4dataE(this);
    return _call0;
        }
        default: abort();
        }
    }
}

void _EN3std12StringBuffer4initE6string(struct _12StringBuffer* this, struct _6string s) {
    struct _4ListI4charE _alloca0;
    struct _6string _alloca1;
    struct _14StringIterator __iterator2;
    struct _6string _alloca3;
    char ch4;
    struct _4ListI4charE* _const_get_element_ptr5;
    int _call6;
    int _binary_op7;
    struct _4ListI4charE _load8;
    struct _14StringIterator _call9;
    _Bool _call10;
    char _call11;
    struct _4ListI4charE* _const_get_element_ptr12;
    char _load13;
    struct _4ListI4charE* _const_get_element_ptr14;
    int _cx_pc = 0;
    while (1) {
        switch (_cx_pc) {
        case 0: {
    _const_get_element_ptr5 = &this->characters;
    *(&_alloca1) = s;
    _call6 = _EN3std6string4sizeE((&_alloca1));
    _binary_op7 = _call6 + 1;
    _EN3std4ListI4charE4initE8capacity3int((&_alloca0), _binary_op7);
    _load8 = *(&_alloca0);
    *_const_get_element_ptr5 = _load8;
    *(&_alloca3) = s;
    _call9 = _EN3std6string8iteratorE((&_alloca3));
    *(&__iterator2) = _call9;
    _cx_pc = 1;
    break;
        }
        case 1: {
    _call10 = _EN3std14StringIterator8hasValueE((&__iterator2));
    if (_call10) {
        _cx_pc = 2;
    } else {
        _cx_pc = 4;
    }
    break;
        }
        case 2: {
    _call11 = _EN3std14StringIterator5valueE((&__iterator2));
    *(&ch4) = _call11;
    _const_get_element_ptr12 = &this->characters;
    _load13 = *(&ch4);
    _EN3std4ListI4charE4pushE4char(_const_get_element_ptr12, _load13);
    _cx_pc = 3;
    break;
        }
        case 3: {
    _EN3std14StringIterator9incrementE((&__iterator2));
    _cx_pc = 1;
    break;
        }
        case 4: {
    _const_get_element_ptr14 = &this->characters;
    _EN3std4ListI4charE4pushE4char(_const_get_element_ptr14, 0);
    return;
        }
        default: abort();
        }
    }
}

void _EN3std10assertFailEP4char(char const* message) {
    struct _4FILE* stream0;
    struct _4FILE* _call1;
    struct _4FILE* _load2;
    _Bool _binary_op3;
    struct _4FILE* _load4;
    _Bool _binary_op5;
    int _call6;
    struct _4FILE* _load7;
    _Bool _binary_op8;
    int _call9;
    int _cx_pc = 0;
    while (1) {
        switch (_cx_pc) {
        case 0: {
    _call1 = fdopen(2, "w");
    *(&stream0) = _call1;
    _load2 = *(&stream0);
    _binary_op3 = _load2 != NULL;
    if (_binary_op3) {
        _cx_pc = 1;
    } else {
        _cx_pc = 2;
    }
    break;
        }
        case 1: {
    _load4 = *(&stream0);
    _binary_op5 = _load4 == NULL;
    if (_binary_op5) {
        _cx_pc = 4;
    } else {
        _cx_pc = 5;
    }
    break;
        }
        case 2: {
    _cx_pc = 3;
    break;
        }
        case 3: {
    _EN3std12abortWrapperE();
    return;
        }
        case 4: {
    _EN3std10assertFailEP4char("Unwrap failed at stdio.cx:132:17\n");
    _cx_pc = 5;
    break;
        }
        case 5: {
    _call6 = fprintf(_load4, "%s", message);
    _load7 = *(&stream0);
    _binary_op8 = _load7 == NULL;
    if (_binary_op8) {
        _cx_pc = 6;
    } else {
        _cx_pc = 7;
    }
    break;
        }
        case 6: {
    _EN3std10assertFailEP4char("Unwrap failed at stdio.cx:133:16\n");
    _cx_pc = 7;
    break;
        }
        case 7: {
    _call9 = fclose(_load7);
    _cx_pc = 3;
    break;
        }
        default: abort();
        }
    }
}

void _EN3std12StringBuffer4initE17uninitializedSize3int(struct _12StringBuffer* this, int uninitializedSize) {
    struct _4ListI4charE _alloca0;
    struct _4ListI4charE* _const_get_element_ptr1;
    int _binary_op2;
    struct _4ListI4charE _load3;
    struct _4ListI4charE* _const_get_element_ptr4;
    int _cx_pc = 0;
    while (1) {
        switch (_cx_pc) {
        case 0: {
    _const_get_element_ptr1 = &this->characters;
    _binary_op2 = uninitializedSize + 1;
    _EN3std4ListI4charE4initE17uninitializedSize3int((&_alloca0), _binary_op2);
    _load3 = *(&_alloca0);
    *_const_get_element_ptr1 = _load3;
    _const_get_element_ptr4 = &this->characters;
    _EN3std4ListI4charEixaE3int4char(_const_get_element_ptr4, uninitializedSize, 0);
    return;
        }
        default: abort();
        }
    }
}

char* _EN3std12StringBuffer4dataE(struct _12StringBuffer* this) {
    struct _4ListI4charE* _const_get_element_ptr0;
    char* _call1;
    int _cx_pc = 0;
    while (1) {
        switch (_cx_pc) {
        case 0: {
    _const_get_element_ptr0 = &this->characters;
    _call1 = _EN3std4ListI4charE4dataE(_const_get_element_ptr0);
    return _call1;
        }
        default: abort();
        }
    }
}

_Bool _EN3std9writeFileE6string6string(struct _6string path, struct _6string content) {
    struct _4FILE* file0;
    struct _12StringBuffer _alloca1;
    struct _6string _alloca2;
    struct _6string _alloca3;
    char* _call4;
    struct _4FILE* _call5;
    struct _4FILE* _load6;
    _Bool _binary_op7;
    char* _call8;
    void const* _cast9;
    int _call10;
    uint64_t _cast11;
    struct _4FILE* _load12;
    _Bool _binary_op13;
    struct _4FILE* _load14;
    _Bool _binary_op15;
    int _call16;
    int _cx_pc = 0;
    while (1) {
        switch (_cx_pc) {
        case 0: {
    _EN3std12StringBuffer4initE6string((&_alloca1), path);
    _call4 = _EN3std12StringBuffer7cStringE((&_alloca1));
    _call5 = fopen(_call4, "wb");
    *(&file0) = _call5;
    _load6 = *(&file0);
    _binary_op7 = _load6 == NULL;
    if (_binary_op7) {
        _cx_pc = 1;
    } else {
        _cx_pc = 2;
    }
    break;
        }
        case 1: {
    return false;
        }
        case 2: {
    _cx_pc = 3;
    break;
        }
        case 3: {
    *(&_alloca2) = content;
    _call8 = _EN3std6string4dataE((&_alloca2));
    _cast9 = (void const*) _call8;
    *(&_alloca3) = content;
    _call10 = _EN3std6string4sizeE((&_alloca3));
    _cast11 = (uint64_t) _call10;
    _load12 = *(&file0);
    _binary_op13 = _load12 == NULL;
    if (_binary_op13) {
        _cx_pc = 4;
    } else {
        _cx_pc = 5;
    }
    break;
        }
        case 4: {
    _EN3std10assertFailEP4char("Unwrap failed at stdio.cx:125:66\n");
    _cx_pc = 5;
    break;
        }
        case 5: {
    fwrite(_cast9, sizeof(char), _cast11, _load12);
    _load14 = *(&file0);
    _binary_op15 = _load14 == NULL;
    if (_binary_op15) {
        _cx_pc = 6;
    } else {
        _cx_pc = 7;
    }
    break;
        }
        case 6: {
    _EN3std10assertFailEP4char("Unwrap failed at stdio.cx:123:18\n");
    _cx_pc = 7;
    break;
        }
        case 7: {
    _call16 = fclose(_load14);
    return true;
        }
        default: abort();
        }
    }
}

char* _EN3std6string4dataE(struct _6string* this) {
    struct _8ArrayRefI4charE* _const_get_element_ptr0;
    char* _call1;
    int _cx_pc = 0;
    while (1) {
        switch (_cx_pc) {
        case 0: {
    _const_get_element_ptr0 = &this->characters;
    _call1 = _EN3std8ArrayRefI4charE4dataE(_const_get_element_ptr0);
    return _call1;
        }
        default: abort();
        }
    }
}

int _EN3std6string4sizeE(struct _6string* this) {
    struct _8ArrayRefI4charE* _const_get_element_ptr0;
    int _call1;
    int _cx_pc = 0;
    while (1) {
        switch (_cx_pc) {
        case 0: {
    _const_get_element_ptr0 = &this->characters;
    _call1 = _EN3std8ArrayRefI4charE4sizeE(_const_get_element_ptr0);
    return _call1;
        }
        default: abort();
        }
    }
}

char _EN3std6stringixE3int(struct _6string* this, int index) {
    struct _8ArrayRefI4charE* _const_get_element_ptr0;
    char* _call1;
    char _load2;
    int _cx_pc = 0;
    while (1) {
        switch (_cx_pc) {
        case 0: {
    _const_get_element_ptr0 = &this->characters;
    _call1 = _EN3std8ArrayRefI4charEixE3int(_const_get_element_ptr0, index);
    _load2 = *_call1;
    return _load2;
        }
        default: abort();
        }
    }
}

_Bool _EN3stdeqEP4char6string(char* a, struct _6string b) {
    struct _6string _alloca0;
    struct _6string _load1;
    _Bool _call2;
    int _cx_pc = 0;
    while (1) {
        switch (_cx_pc) {
        case 0: {
    _EN3std6string4initEP4char((&_alloca0), a);
    _load1 = *(&_alloca0);
    _call2 = _EN3stdeqE6string6string(_load1, b);
    return _call2;
        }
        default: abort();
        }
    }
}

_Bool _EN3stdneEP4char6string(char* a, struct _6string b) {
    struct _6string _alloca0;
    struct _6string _alloca1;
    _Bool _call2;
    int _cx_pc = 0;
    while (1) {
        switch (_cx_pc) {
        case 0: {
    _EN3std6string4initEP4char((&_alloca0), a);
    *(&_alloca1) = b;
    _call2 = _EN3stdneI6stringEEP6stringP6string((&_alloca0), (&_alloca1));
    return _call2;
        }
        default: abort();
        }
    }
}

_Bool _EN3stdeqE6stringP4char(struct _6string a, char* b) {
    struct _6string _alloca0;
    struct _6string _load1;
    _Bool _call2;
    int _cx_pc = 0;
    while (1) {
        switch (_cx_pc) {
        case 0: {
    _EN3std6string4initEP4char((&_alloca0), b);
    _load1 = *(&_alloca0);
    _call2 = _EN3stdeqE6string6string(a, _load1);
    return _call2;
        }
        default: abort();
        }
    }
}

_Bool _EN3stdneE6stringP4char(struct _6string a, char* b) {
    struct _6string _alloca0;
    struct _6string _alloca1;
    _Bool _call2;
    int _cx_pc = 0;
    while (1) {
        switch (_cx_pc) {
        case 0: {
    *(&_alloca0) = a;
    _EN3std6string4initEP4char((&_alloca1), b);
    _call2 = _EN3stdneI6stringEEP6stringP6string((&_alloca0), (&_alloca1));
    return _call2;
        }
        default: abort();
        }
    }
}

void _EN3std7printlnI6string3int6stringEEP6stringP3intP6string(struct _6string* _0, int* _1, struct _6string* _2) {
    int _cx_pc = 0;
    while (1) {
        switch (_cx_pc) {
        case 0: {
    _EN3std5printI6stringEEP6string(_0);
    _EN3std5printI3intEEP3int(_1);
    _EN3std5printI6stringEEP6string(_2);
    _EN3std5printI4charEE4char(10);
    return;
        }
        default: abort();
        }
    }
}

void _EN3std4ListI4charE6deinitE(struct _4ListI4charE* this) {
    struct _13ArrayIteratorI4charE __iterator0;
    char* element1;
    int* _const_get_element_ptr2;
    int _load3;
    _Bool _binary_op4;
    struct _13ArrayIteratorI4charE _call5;
    _Bool _call6;
    char* _call7;
    char** _const_get_element_ptr8;
    char* _load9;
    int _cx_pc = 0;
    while (1) {
        switch (_cx_pc) {
        case 0: {
    _const_get_element_ptr2 = &this->capacity;
    _load3 = *_const_get_element_ptr2;
    _binary_op4 = _load3 != 0;
    if (_binary_op4) {
        _cx_pc = 1;
    } else {
        _cx_pc = 2;
    }
    break;
        }
        case 1: {
    _call5 = _EN3std4ListI4charE8iteratorE(this);
    *(&__iterator0) = _call5;
    _cx_pc = 4;
    break;
        }
        case 2: {
    _cx_pc = 3;
    break;
        }
        case 3: {
    return;
        }
        case 4: {
    _call6 = _EN3std13ArrayIteratorI4charE8hasValueE((&__iterator0));
    if (_call6) {
        _cx_pc = 5;
    } else {
        _cx_pc = 7;
    }
    break;
        }
        case 5: {
    _call7 = _EN3std13ArrayIteratorI4charE5valueE((&__iterator0));
    *(&element1) = _call7;
    _cx_pc = 6;
    break;
        }
        case 6: {
    _EN3std13ArrayIteratorI4charE9incrementE((&__iterator0));
    _cx_pc = 4;
    break;
        }
        case 7: {
    _const_get_element_ptr8 = &this->buffer;
    _load9 = *_const_get_element_ptr8;
    _EN3std10deallocateIAU_4charEEAU_4char(_load9);
    _cx_pc = 3;
    break;
        }
        default: abort();
        }
    }
}

void _EN3std4ListI4charE4initE(struct _4ListI4charE* this) {
    int* _const_get_element_ptr0;
    int* _const_get_element_ptr1;
    int _cx_pc = 0;
    while (1) {
        switch (_cx_pc) {
        case 0: {
    _const_get_element_ptr0 = &this->size;
    *_const_get_element_ptr0 = 0;
    _const_get_element_ptr1 = &this->capacity;
    *_const_get_element_ptr1 = 0;
    return;
        }
        default: abort();
        }
    }
}

void _EN3std4ListI4charE4pushE4char(struct _4ListI4charE* this, char element) {
    int* _const_get_element_ptr0;
    int _load1;
    int* _const_get_element_ptr2;
    int _load3;
    _Bool _binary_op4;
    char** _const_get_element_ptr5;
    char* _load6;
    int* _const_get_element_ptr7;
    int _load8;
    char* _get_element_ptr9;
    int* _const_get_element_ptr10;
    int _load11;
    int _binary_op12;
    int _cx_pc = 0;
    while (1) {
        switch (_cx_pc) {
        case 0: {
    _const_get_element_ptr0 = &this->size;
    _load1 = *_const_get_element_ptr0;
    _const_get_element_ptr2 = &this->capacity;
    _load3 = *_const_get_element_ptr2;
    _binary_op4 = _load1 == _load3;
    if (_binary_op4) {
        _cx_pc = 1;
    } else {
        _cx_pc = 2;
    }
    break;
        }
        case 1: {
    _EN3std4ListI4charE4growE(this);
    _cx_pc = 3;
    break;
        }
        case 2: {
    _cx_pc = 3;
    break;
        }
        case 3: {
    _const_get_element_ptr5 = &this->buffer;
    _load6 = *_const_get_element_ptr5;
    _const_get_element_ptr7 = &this->size;
    _load8 = *_const_get_element_ptr7;
    _get_element_ptr9 = &(_load6[_load8]);
    *_get_element_ptr9 = element;
    _const_get_element_ptr10 = &this->size;
    _load11 = *_const_get_element_ptr10;
    _binary_op12 = _load11 + 1;
    *_const_get_element_ptr10 = _binary_op12;
    return;
        }
        default: abort();
        }
    }
}

void _EN3std14StringIterator4initE6string(struct _14StringIterator* this, struct _6string s) {
    struct _6string _alloca0;
    struct _6string _alloca1;
    struct _6string _alloca2;
    char** _const_get_element_ptr3;
    char* _call4;
    char** _const_get_element_ptr5;
    char* _call6;
    int _call7;
    char* _get_element_ptr8;
    int _cx_pc = 0;
    while (1) {
        switch (_cx_pc) {
        case 0: {
    _const_get_element_ptr3 = &this->current;
    *(&_alloca0) = s;
    _call4 = _EN3std6string4dataE((&_alloca0));
    *_const_get_element_ptr3 = _call4;
    _const_get_element_ptr5 = &this->end;
    *(&_alloca1) = s;
    _call6 = _EN3std6string4dataE((&_alloca1));
    *(&_alloca2) = s;
    _call7 = _EN3std6string4sizeE((&_alloca2));
    _get_element_ptr8 = &(_call6[_call7]);
    *_const_get_element_ptr5 = _get_element_ptr8;
    return;
        }
        default: abort();
        }
    }
}

void _EN3std4ListI4charEixaE3int4char(struct _4ListI4charE* this, int index, char element) {
    char** _const_get_element_ptr0;
    char* _load1;
    char* _get_element_ptr2;
    int _cx_pc = 0;
    while (1) {
        switch (_cx_pc) {
        case 0: {
    _const_get_element_ptr0 = &this->buffer;
    _load1 = *_const_get_element_ptr0;
    _get_element_ptr2 = &(_load1[index]);
    *_get_element_ptr2 = element;
    return;
        }
        default: abort();
        }
    }
}

int _EN3std12StringBuffer4sizeE(struct _12StringBuffer* this) {
    struct _4ListI4charE* _const_get_element_ptr0;
    int _call1;
    int _binary_op2;
    int _cx_pc = 0;
    while (1) {
        switch (_cx_pc) {
        case 0: {
    _const_get_element_ptr0 = &this->characters;
    _call1 = _EN3std4ListI4charE4sizeE(_const_get_element_ptr0);
    _binary_op2 = _call1 - 1;
    return _binary_op2;
        }
        default: abort();
        }
    }
}

void _EN3std8ArrayRefI4charE4initEP4char3int(struct _8ArrayRefI4charE* this, char* data, int size) {
    char** _const_get_element_ptr0;
    int* _const_get_element_ptr1;
    int _cx_pc = 0;
    while (1) {
        switch (_cx_pc) {
        case 0: {
    _const_get_element_ptr0 = &this->data;
    *_const_get_element_ptr0 = data;
    _const_get_element_ptr1 = &this->size;
    *_const_get_element_ptr1 = size;
    return;
        }
        default: abort();
        }
    }
}

int _EN3std6string7compareEP6string(struct _6string* this, struct _6string* other) {
    struct _13RangeIteratorI3intE __iterator0;
    struct _5RangeI3intE _alloca1;
    int _alloca2;
    int _alloca3;
    int index4;
    int _call5;
    int _call6;
    int* _call7;
    int _load8;
    struct _13RangeIteratorI3intE _call9;
    _Bool _call10;
    int _call11;
    int _load12;
    char _call13;
    int _load14;
    char _call15;
    _Bool _binary_op16;
    int _call17;
    int _call18;
    _Bool _binary_op19;
    int _load20;
    char _call21;
    int _load22;
    char _call23;
    _Bool _binary_op24;
    int _call25;
    int _call26;
    _Bool _binary_op27;
    int _cx_pc = 0;
    while (1) {
        switch (_cx_pc) {
        case 0: {
    _call5 = _EN3std6string4sizeE(this);
    *(&_alloca2) = _call5;
    _call6 = _EN3std6string4sizeE(other);
    *(&_alloca3) = _call6;
    _call7 = _EN3std3minI3intEEP3intP3int((&_alloca2), (&_alloca3));
    _load8 = *_call7;
    _EN3std5RangeI3intE4initE3int3int((&_alloca1), 0, _load8);
    _call9 = _EN3std5RangeI3intE8iteratorE((&_alloca1));
    *(&__iterator0) = _call9;
    _cx_pc = 1;
    break;
        }
        case 1: {
    _call10 = _EN3std13RangeIteratorI3intE8hasValueE((&__iterator0));
    if (_call10) {
        _cx_pc = 2;
    } else {
        _cx_pc = 4;
    }
    break;
        }
        case 2: {
    _call11 = _EN3std13RangeIteratorI3intE5valueE((&__iterator0));
    *(&index4) = _call11;
    _load12 = *(&index4);
    _call13 = _EN3std6stringixE3int(this, _load12);
    _load14 = *(&index4);
    _call15 = _EN3std6stringixE3int(other, _load14);
    _binary_op16 = _call13 < _call15;
    if (_binary_op16) {
        _cx_pc = 5;
    } else {
        _cx_pc = 6;
    }
    break;
        }
        case 3: {
    _EN3std13RangeIteratorI3intE9incrementE((&__iterator0));
    _cx_pc = 1;
    break;
        }
        case 4: {
    _call17 = _EN3std6string4sizeE(this);
    _call18 = _EN3std6string4sizeE(other);
    _binary_op19 = _call17 < _call18;
    if (_binary_op19) {
        _cx_pc = 11;
    } else {
        _cx_pc = 12;
    }
    break;
        }
        case 5: {
    return 0;
        }
        case 6: {
    _cx_pc = 7;
    break;
        }
        case 7: {
    _load20 = *(&index4);
    _call21 = _EN3std6stringixE3int(this, _load20);
    _load22 = *(&index4);
    _call23 = _EN3std6stringixE3int(other, _load22);
    _binary_op24 = _call21 > _call23;
    if (_binary_op24) {
        _cx_pc = 8;
    } else {
        _cx_pc = 9;
    }
    break;
        }
        case 8: {
    return 2;
        }
        case 9: {
    _cx_pc = 10;
    break;
        }
        case 10: {
    _cx_pc = 3;
    break;
        }
        case 11: {
    return 0;
        }
        case 12: {
    _cx_pc = 13;
    break;
        }
        case 13: {
    _call25 = _EN3std6string4sizeE(this);
    _call26 = _EN3std6string4sizeE(other);
    _binary_op27 = _call25 > _call26;
    if (_binary_op27) {
        _cx_pc = 14;
    } else {
        _cx_pc = 15;
    }
    break;
        }
        case 14: {
    return 2;
        }
        case 15: {
    _cx_pc = 16;
    break;
        }
        case 16: {
    return 1;
        }
        default: abort();
        }
    }
}

void _EN3std13RangeIteratorI3intE4initE5RangeI3intE(struct _13RangeIteratorI3intE* this, struct _5RangeI3intE range) {
    struct _5RangeI3intE _alloca0;
    struct _5RangeI3intE _alloca1;
    int* _const_get_element_ptr2;
    int _call3;
    int* _const_get_element_ptr4;
    int _call5;
    int _cx_pc = 0;
    while (1) {
        switch (_cx_pc) {
        case 0: {
    _const_get_element_ptr2 = &this->current;
    *(&_alloca0) = range;
    _call3 = _EN3std5RangeI3intE5startE((&_alloca0));
    *_const_get_element_ptr2 = _call3;
    _const_get_element_ptr4 = &this->end;
    *(&_alloca1) = range;
    _call5 = _EN3std5RangeI3intE3endE((&_alloca1));
    *_const_get_element_ptr4 = _call5;
    return;
        }
        default: abort();
        }
    }
}

struct _12StringBuffer _EN3std4char8toStringE(char* this) {
    struct _12StringBuffer result0;
    struct _12StringBuffer _load1;
    int _cx_pc = 0;
    while (1) {
        switch (_cx_pc) {
        case 0: {
    _EN3std12StringBuffer4initE((&result0));
    _EN3std4char5printEP12StringBuffer(this, (&result0));
    _load1 = *(&result0);
    return _load1;
        }
        default: abort();
        }
    }
}

void _EN3std4ListI4charE4initE8capacity3int(struct _4ListI4charE* this, int capacity) {
    int _cx_pc = 0;
    while (1) {
        switch (_cx_pc) {
        case 0: {
    _EN3std4ListI4charE4initE(this);
    _EN3std4ListI4charE7reserveE3int(this, capacity);
    return;
        }
        default: abort();
        }
    }
}

void _EN3std4ListI4charE4initE17uninitializedSize3int(struct _4ListI4charE* this, int uninitializedSize) {
    char** _const_get_element_ptr0;
    char* _call1;
    int* _const_get_element_ptr2;
    int* _const_get_element_ptr3;
    int _cx_pc = 0;
    while (1) {
        switch (_cx_pc) {
        case 0: {
    _const_get_element_ptr0 = &this->buffer;
    _call1 = _EN3std13allocateArrayI4charEE3int(uninitializedSize);
    *_const_get_element_ptr0 = _call1;
    _const_get_element_ptr2 = &this->size;
    *_const_get_element_ptr2 = uninitializedSize;
    _const_get_element_ptr3 = &this->capacity;
    *_const_get_element_ptr3 = uninitializedSize;
    return;
        }
        default: abort();
        }
    }
}

char* _EN3std4ListI4charE4dataE(struct _4ListI4charE* this) {
    char** _const_get_element_ptr0;
    char* _load1;
    int _cx_pc = 0;
    while (1) {
        switch (_cx_pc) {
        case 0: {
    _const_get_element_ptr0 = &this->buffer;
    _load1 = *_const_get_element_ptr0;
    return _load1;
        }
        default: abort();
        }
    }
}

char* _EN3std8ArrayRefI4charE4dataE(struct _8ArrayRefI4charE* this) {
    char** _const_get_element_ptr0;
    char* _load1;
    int _cx_pc = 0;
    while (1) {
        switch (_cx_pc) {
        case 0: {
    _const_get_element_ptr0 = &this->data;
    _load1 = *_const_get_element_ptr0;
    return _load1;
        }
        default: abort();
        }
    }
}

int _EN3std8ArrayRefI4charE4sizeE(struct _8ArrayRefI4charE* this) {
    int* _const_get_element_ptr0;
    int _load1;
    int _cx_pc = 0;
    while (1) {
        switch (_cx_pc) {
        case 0: {
    _const_get_element_ptr0 = &this->size;
    _load1 = *_const_get_element_ptr0;
    return _load1;
        }
        default: abort();
        }
    }
}

char* _EN3std8ArrayRefI4charEixE3int(struct _8ArrayRefI4charE* this, int index) {
    _Bool _cxp_or;
    struct _6string __str0;
    _Bool _binary_op1;
    int _call2;
    _Bool _binary_op3;
    struct _6string _load4;
    char** _const_get_element_ptr5;
    char* _load6;
    char* _get_element_ptr7;
    int _cx_pc = 0;
    while (1) {
        switch (_cx_pc) {
        case 0: {
    _binary_op1 = index < 0;
    if (_binary_op1) {
        _cxp_or = _binary_op1;
        _cx_pc = 2;
    } else {
        _cx_pc = 1;
    }
    break;
        }
        case 1: {
    _call2 = _EN3std8ArrayRefI4charE4sizeE(this);
    _binary_op3 = index >= _call2;
    _cxp_or = _binary_op3; // branch argument
    _cx_pc = 2;
    break;
        }
        case 2: {
    if (_cxp_or) {
        _cx_pc = 3;
    } else {
        _cx_pc = 4;
    }
    break;
        }
        case 3: {
    _EN3std6string4initEP4char3int((&__str0), "operator[]", 10);
    _load4 = *(&__str0);
    _EN3std8ArrayRefI4charE16indexOutOfBoundsE6string3int(this, _load4, index);
    _cx_pc = 5;
    break;
        }
        case 4: {
    _cx_pc = 5;
    break;
        }
        case 5: {
    _const_get_element_ptr5 = &this->data;
    _load6 = *_const_get_element_ptr5;
    _get_element_ptr7 = &(_load6[index]);
    return _get_element_ptr7;
        }
        default: abort();
        }
    }
}

void _EN3std5printI6stringEEP6string(struct _6string* value) {
    struct _12StringBuffer s0;
    struct _12StringBuffer _call1;
    int _call2;
    char* _call3;
    int _call4;
    int _cx_pc = 0;
    while (1) {
        switch (_cx_pc) {
        case 0: {
    _call1 = _EN3std6string8toStringE(value);
    *(&s0) = _call1;
    _call2 = _EN3std12StringBuffer4sizeE((&s0));
    _call3 = _EN3std12StringBuffer4dataE((&s0));
    _call4 = printf("%.*s", _call2, _call3);
    _EN3std12StringBuffer6deinitE((&s0));
    return;
        }
        default: abort();
        }
    }
}

void _EN3std5printI3intEEP3int(int* value) {
    struct _12StringBuffer s0;
    struct _12StringBuffer _call1;
    int _call2;
    char* _call3;
    int _call4;
    int _cx_pc = 0;
    while (1) {
        switch (_cx_pc) {
        case 0: {
    _call1 = _EN3std3int8toStringE(value);
    *(&s0) = _call1;
    _call2 = _EN3std12StringBuffer4sizeE((&s0));
    _call3 = _EN3std12StringBuffer4dataE((&s0));
    _call4 = printf("%.*s", _call2, _call3);
    _EN3std12StringBuffer6deinitE((&s0));
    return;
        }
        default: abort();
        }
    }
}

struct _13ArrayIteratorI4charE _EN3std4ListI4charE8iteratorE(struct _4ListI4charE* this) {
    struct _13ArrayIteratorI4charE _alloca0;
    struct _8ArrayRefI4charE _alloca1;
    struct _8ArrayRefI4charE _load2;
    struct _13ArrayIteratorI4charE _load3;
    int _cx_pc = 0;
    while (1) {
        switch (_cx_pc) {
        case 0: {
    _EN3std8ArrayRefI4charE4initEP4ListI4charE((&_alloca1), this);
    _load2 = *(&_alloca1);
    _EN3std13ArrayIteratorI4charE4initE8ArrayRefI4charE((&_alloca0), _load2);
    _load3 = *(&_alloca0);
    return _load3;
        }
        default: abort();
        }
    }
}

_Bool _EN3std13ArrayIteratorI4charE8hasValueE(struct _13ArrayIteratorI4charE* this) {
    char** _const_get_element_ptr0;
    char* _load1;
    char** _const_get_element_ptr2;
    char* _load3;
    _Bool _binary_op4;
    int _cx_pc = 0;
    while (1) {
        switch (_cx_pc) {
        case 0: {
    _const_get_element_ptr0 = &this->current;
    _load1 = *_const_get_element_ptr0;
    _const_get_element_ptr2 = &this->end;
    _load3 = *_const_get_element_ptr2;
    _binary_op4 = _load1 != _load3;
    return _binary_op4;
        }
        default: abort();
        }
    }
}

char* _EN3std13ArrayIteratorI4charE5valueE(struct _13ArrayIteratorI4charE* this) {
    char** _const_get_element_ptr0;
    char* _load1;
    int _cx_pc = 0;
    while (1) {
        switch (_cx_pc) {
        case 0: {
    _const_get_element_ptr0 = &this->current;
    _load1 = *_const_get_element_ptr0;
    return _load1;
        }
        default: abort();
        }
    }
}

void _EN3std13ArrayIteratorI4charE9incrementE(struct _13ArrayIteratorI4charE* this) {
    char** _const_get_element_ptr0;
    char* _load1;
    char* _get_element_ptr2;
    int _cx_pc = 0;
    while (1) {
        switch (_cx_pc) {
        case 0: {
    _const_get_element_ptr0 = &this->current;
    _load1 = *_const_get_element_ptr0;
    _get_element_ptr2 = &(_load1[1]);
    *_const_get_element_ptr0 = _get_element_ptr2;
    return;
        }
        default: abort();
        }
    }
}

void _EN3std10deallocateIAU_4charEEAU_4char(char* allocation) {
    void* _cast0;
    int _cx_pc = 0;
    while (1) {
        switch (_cx_pc) {
        case 0: {
    _cast0 = (void*) allocation;
    free(_cast0);
    return;
        }
        default: abort();
        }
    }
}

void _EN3std4ListI4charE4growE(struct _4ListI4charE* this) {
    int* _const_get_element_ptr0;
    int _load1;
    _Bool _binary_op2;
    int* _const_get_element_ptr3;
    int _load4;
    int _binary_op5;
    int _cx_pc = 0;
    while (1) {
        switch (_cx_pc) {
        case 0: {
    _const_get_element_ptr0 = &this->capacity;
    _load1 = *_const_get_element_ptr0;
    _binary_op2 = _load1 == 0;
    if (_binary_op2) {
        _cx_pc = 1;
    } else {
        _cx_pc = 2;
    }
    break;
        }
        case 1: {
    _EN3std4ListI4charE7reserveE3int(this, 1);
    _cx_pc = 3;
    break;
        }
        case 2: {
    _const_get_element_ptr3 = &this->capacity;
    _load4 = *_const_get_element_ptr3;
    _binary_op5 = _load4 * 2;
    _EN3std4ListI4charE7reserveE3int(this, _binary_op5);
    _cx_pc = 3;
    break;
        }
        case 3: {
    return;
        }
        default: abort();
        }
    }
}

int _EN3std4ListI4charE4sizeE(struct _4ListI4charE* this) {
    int* _const_get_element_ptr0;
    int _load1;
    int _cx_pc = 0;
    while (1) {
        switch (_cx_pc) {
        case 0: {
    _const_get_element_ptr0 = &this->size;
    _load1 = *_const_get_element_ptr0;
    return _load1;
        }
        default: abort();
        }
    }
}

int* _EN3std3minI3intEEP3intP3int(int* a, int* b) {
    int _load0;
    int _load1;
    _Bool _binary_op2;
    int _cx_pc = 0;
    while (1) {
        switch (_cx_pc) {
        case 0: {
    _load0 = *a;
    _load1 = *b;
    _binary_op2 = _load0 < _load1;
    if (_binary_op2) {
        _cx_pc = 1;
    } else {
        _cx_pc = 2;
    }
    break;
        }
        case 1: {
    return a;
        }
        case 2: {
    _cx_pc = 3;
    break;
        }
        case 3: {
    return b;
        }
        default: abort();
        }
    }
}

int _EN3std5RangeI3intE5startE(struct _5RangeI3intE* this) {
    int* _const_get_element_ptr0;
    int _load1;
    int _cx_pc = 0;
    while (1) {
        switch (_cx_pc) {
        case 0: {
    _const_get_element_ptr0 = &this->start;
    _load1 = *_const_get_element_ptr0;
    return _load1;
        }
        default: abort();
        }
    }
}

int _EN3std5RangeI3intE3endE(struct _5RangeI3intE* this) {
    int* _const_get_element_ptr0;
    int _load1;
    int _cx_pc = 0;
    while (1) {
        switch (_cx_pc) {
        case 0: {
    _const_get_element_ptr0 = &this->end;
    _load1 = *_const_get_element_ptr0;
    return _load1;
        }
        default: abort();
        }
    }
}

void _EN3std4char5printEP12StringBuffer(char* this, struct _12StringBuffer* stream) {
    struct _6string _alloca0;
    struct _6string _load1;
    _Bool _call2;
    int _cx_pc = 0;
    while (1) {
        switch (_cx_pc) {
        case 0: {
    _EN3std6string4initEP4char3int((&_alloca0), this, 1);
    _load1 = *(&_alloca0);
    _call2 = _EN3std12StringBuffer5writeE6string(stream, _load1);
    return;
        }
        default: abort();
        }
    }
}

void _EN3std4ListI4charE7reserveE3int(struct _4ListI4charE* this, int minimumCapacity) {
    char* newBuffer0;
    struct _13RangeIteratorI3intE __iterator1;
    struct _5RangeI3intE _alloca2;
    int index3;
    char* source4;
    char* target5;
    int* _const_get_element_ptr6;
    int _load7;
    _Bool _binary_op8;
    char* _call9;
    int* _const_get_element_ptr10;
    int _load11;
    struct _13RangeIteratorI3intE _call12;
    _Bool _call13;
    int _call14;
    char** _const_get_element_ptr15;
    char* _load16;
    int _load17;
    char* _get_element_ptr18;
    char* _load19;
    int _load20;
    char* _get_element_ptr21;
    char* _load22;
    char* _load23;
    char _load24;
    int* _const_get_element_ptr25;
    int _load26;
    _Bool _binary_op27;
    char** _const_get_element_ptr28;
    char* _load29;
    char** _const_get_element_ptr30;
    char* _load31;
    int* _const_get_element_ptr32;
    int _cx_pc = 0;
    while (1) {
        switch (_cx_pc) {
        case 0: {
    _const_get_element_ptr6 = &this->capacity;
    _load7 = *_const_get_element_ptr6;
    _binary_op8 = minimumCapacity > _load7;
    if (_binary_op8) {
        _cx_pc = 1;
    } else {
        _cx_pc = 2;
    }
    break;
        }
        case 1: {
    _call9 = _EN3std13allocateArrayI4charEE3int(minimumCapacity);
    *(&newBuffer0) = _call9;
    _const_get_element_ptr10 = &this->size;
    _load11 = *_const_get_element_ptr10;
    _EN3std5RangeI3intE4initE3int3int((&_alloca2), 0, _load11);
    _call12 = _EN3std5RangeI3intE8iteratorE((&_alloca2));
    *(&__iterator1) = _call12;
    _cx_pc = 4;
    break;
        }
        case 2: {
    _cx_pc = 3;
    break;
        }
        case 3: {
    return;
        }
        case 4: {
    _call13 = _EN3std13RangeIteratorI3intE8hasValueE((&__iterator1));
    if (_call13) {
        _cx_pc = 5;
    } else {
        _cx_pc = 7;
    }
    break;
        }
        case 5: {
    _call14 = _EN3std13RangeIteratorI3intE5valueE((&__iterator1));
    *(&index3) = _call14;
    _const_get_element_ptr15 = &this->buffer;
    _load16 = *_const_get_element_ptr15;
    _load17 = *(&index3);
    _get_element_ptr18 = &(_load16[_load17]);
    *(&source4) = _get_element_ptr18;
    _load19 = *(&newBuffer0);
    _load20 = *(&index3);
    _get_element_ptr21 = &(_load19[_load20]);
    *(&target5) = _get_element_ptr21;
    _load22 = *(&target5);
    _load23 = *(&source4);
    _load24 = *_load23;
    *_load22 = _load24;
    _cx_pc = 6;
    break;
        }
        case 6: {
    _EN3std13RangeIteratorI3intE9incrementE((&__iterator1));
    _cx_pc = 4;
    break;
        }
        case 7: {
    _const_get_element_ptr25 = &this->capacity;
    _load26 = *_const_get_element_ptr25;
    _binary_op27 = _load26 != 0;
    if (_binary_op27) {
        _cx_pc = 8;
    } else {
        _cx_pc = 9;
    }
    break;
        }
        case 8: {
    _const_get_element_ptr28 = &this->buffer;
    _load29 = *_const_get_element_ptr28;
    _EN3std10deallocateIAU_4charEEAU_4char(_load29);
    _cx_pc = 10;
    break;
        }
        case 9: {
    _cx_pc = 10;
    break;
        }
        case 10: {
    _const_get_element_ptr30 = &this->buffer;
    _load31 = *(&newBuffer0);
    *_const_get_element_ptr30 = _load31;
    _const_get_element_ptr32 = &this->capacity;
    *_const_get_element_ptr32 = minimumCapacity;
    _cx_pc = 3;
    break;
        }
        default: abort();
        }
    }
}

char* _EN3std13allocateArrayI4charEE3int(int size) {
    uint64_t _cast0;
    uint64_t _binary_op1;
    void* _call2;
    _Bool _binary_op3;
    char* _cast4;
    int _cx_pc = 0;
    while (1) {
        switch (_cx_pc) {
        case 0: {
    _cast0 = (uint64_t) size;
    _binary_op1 = sizeof(char) * _cast0;
    _call2 = malloc(_binary_op1);
    _binary_op3 = _call2 == NULL;
    if (_binary_op3) {
        _cx_pc = 1;
    } else {
        _cx_pc = 2;
    }
    break;
        }
        case 1: {
    _EN3std10assertFailEP4char("Unwrap failed at allocate.cx:36:61\n");
    _cx_pc = 2;
    break;
        }
        case 2: {
    _cast4 = (char*) _call2;
    return _cast4;
        }
        default: abort();
        }
    }
}

void _EN3std8ArrayRefI4charE16indexOutOfBoundsE6string3int(struct _8ArrayRefI4charE* this, struct _6string function, int index) {
    struct _6string __str0;
    struct _6string _alloca1;
    struct _6string __str2;
    int _alloca3;
    struct _6string __str4;
    int _alloca5;
    int _call6;
    int _cx_pc = 0;
    while (1) {
        switch (_cx_pc) {
        case 0: {
    _EN3std6string4initEP4char3int((&__str0), "ArrayRef.", 9);
    *(&_alloca1) = function;
    _EN3std6string4initEP4char3int((&__str2), ": index ", 8);
    *(&_alloca3) = index;
    _EN3std6string4initEP4char3int((&__str4), " is out of bounds, size is ", 27);
    _call6 = _EN3std8ArrayRefI4charE4sizeE(this);
    *(&_alloca5) = _call6;
    _EN3std5abortI6string6string6string3int6string3intEEP6stringP6stringP6stringP3intP6stringP3int((&__str0), (&_alloca1), (&__str2), (&_alloca3), (&__str4), (&_alloca5));
    return;
        }
        default: abort();
        }
    }
}

struct _12StringBuffer _EN3std6string8toStringE(struct _6string* this) {
    struct _12StringBuffer result0;
    struct _12StringBuffer _load1;
    int _cx_pc = 0;
    while (1) {
        switch (_cx_pc) {
        case 0: {
    _EN3std12StringBuffer4initE((&result0));
    _EN3std6string5printEP12StringBuffer(this, (&result0));
    _load1 = *(&result0);
    return _load1;
        }
        default: abort();
        }
    }
}

struct _12StringBuffer _EN3std3int8toStringE(int* this) {
    struct _12StringBuffer result0;
    struct _12StringBuffer _load1;
    int _cx_pc = 0;
    while (1) {
        switch (_cx_pc) {
        case 0: {
    _EN3std12StringBuffer4initE((&result0));
    _EN3std3int5printEP12StringBuffer(this, (&result0));
    _load1 = *(&result0);
    return _load1;
        }
        default: abort();
        }
    }
}

void _EN3std13ArrayIteratorI4charE4initE8ArrayRefI4charE(struct _13ArrayIteratorI4charE* this, struct _8ArrayRefI4charE array) {
    struct _8ArrayRefI4charE _alloca0;
    struct _8ArrayRefI4charE _alloca1;
    struct _8ArrayRefI4charE _alloca2;
    char** _const_get_element_ptr3;
    char* _call4;
    char** _const_get_element_ptr5;
    char* _call6;
    int _call7;
    char* _get_element_ptr8;
    int _cx_pc = 0;
    while (1) {
        switch (_cx_pc) {
        case 0: {
    _const_get_element_ptr3 = &this->current;
    *(&_alloca0) = array;
    _call4 = _EN3std8ArrayRefI4charE4dataE((&_alloca0));
    *_const_get_element_ptr3 = _call4;
    _const_get_element_ptr5 = &this->end;
    *(&_alloca1) = array;
    _call6 = _EN3std8ArrayRefI4charE4dataE((&_alloca1));
    *(&_alloca2) = array;
    _call7 = _EN3std8ArrayRefI4charE4sizeE((&_alloca2));
    _get_element_ptr8 = &(_call6[_call7]);
    *_const_get_element_ptr5 = _get_element_ptr8;
    return;
        }
        default: abort();
        }
    }
}

void _EN3std8ArrayRefI4charE4initEP4ListI4charE(struct _8ArrayRefI4charE* this, struct _4ListI4charE* list) {
    char** _const_get_element_ptr0;
    char* _call1;
    int* _const_get_element_ptr2;
    int _call3;
    int _cx_pc = 0;
    while (1) {
        switch (_cx_pc) {
        case 0: {
    _const_get_element_ptr0 = &this->data;
    _call1 = _EN3std4ListI4charE4dataE(list);
    *_const_get_element_ptr0 = _call1;
    _const_get_element_ptr2 = &this->size;
    _call3 = _EN3std4ListI4charE4sizeE(list);
    *_const_get_element_ptr2 = _call3;
    return;
        }
        default: abort();
        }
    }
}

void _EN3std5abortI6string6string6string3int6string3intEEP6stringP6stringP6stringP3intP6stringP3int(struct _6string* _0, struct _6string* _1, struct _6string* _2, int* _3, struct _6string* _4, int* _5) {
    struct _16OutputFileStream _alloca0;
    struct _16OutputFileStream _alloca1;
    struct _16OutputFileStream _alloca2;
    struct _16OutputFileStream _alloca3;
    struct _16OutputFileStream _alloca4;
    struct _16OutputFileStream _alloca5;
    struct _16OutputFileStream _alloca6;
    char _alloca7;
    struct _16OutputFileStream _call8;
    struct _16OutputFileStream _call9;
    struct _16OutputFileStream _call10;
    struct _16OutputFileStream _call11;
    struct _16OutputFileStream _call12;
    struct _16OutputFileStream _call13;
    struct _16OutputFileStream _call14;
    int _cx_pc = 0;
    while (1) {
        switch (_cx_pc) {
        case 0: {
    _call8 = _EN3std6stderrE();
    *(&_alloca0) = _call8;
    _EN3std16OutputFileStream5writeI6stringEEP6string((&_alloca0), _0);
    _call9 = _EN3std6stderrE();
    *(&_alloca1) = _call9;
    _EN3std16OutputFileStream5writeI6stringEEP6string((&_alloca1), _1);
    _call10 = _EN3std6stderrE();
    *(&_alloca2) = _call10;
    _EN3std16OutputFileStream5writeI6stringEEP6string((&_alloca2), _2);
    _call11 = _EN3std6stderrE();
    *(&_alloca3) = _call11;
    _EN3std16OutputFileStream5writeI3intEEP3int((&_alloca3), _3);
    _call12 = _EN3std6stderrE();
    *(&_alloca4) = _call12;
    _EN3std16OutputFileStream5writeI6stringEEP6string((&_alloca4), _4);
    _call13 = _EN3std6stderrE();
    *(&_alloca5) = _call13;
    _EN3std16OutputFileStream5writeI3intEEP3int((&_alloca5), _5);
    _call14 = _EN3std6stderrE();
    *(&_alloca6) = _call14;
    *(&_alloca7) = 10;
    _EN3std16OutputFileStream5writeI4charEEP4char((&_alloca6), (&_alloca7));
    _EN3std12abortWrapperE();
    abort();
        }
        default: abort();
        }
    }
}

void _EN3std6string5printEP12StringBuffer(struct _6string* this, struct _12StringBuffer* stream) {
    struct _6string _load0;
    _Bool _call1;
    int _cx_pc = 0;
    while (1) {
        switch (_cx_pc) {
        case 0: {
    _load0 = *this;
    _call1 = _EN3std12StringBuffer5writeE6string(stream, _load0);
    return;
        }
        default: abort();
        }
    }
}

void _EN3std3int5printEP12StringBuffer(int* this, struct _12StringBuffer* stream) {
    int _load0;
    int64_t _cast1;
    int _cx_pc = 0;
    while (1) {
        switch (_cx_pc) {
        case 0: {
    _load0 = *this;
    _cast1 = (int64_t) _load0;
    _EN3std11printSignedE5int64P12StringBuffer(_cast1, stream);
    return;
        }
        default: abort();
        }
    }
}

void _EN3std16OutputFileStream5writeI6stringEEP6string(struct _16OutputFileStream* this, struct _6string* value) {
    struct _12StringBuffer s0;
    struct _12StringBuffer _call1;
    struct _4FILE** _const_get_element_ptr2;
    struct _4FILE* _load3;
    _Bool _binary_op4;
    int _call5;
    char* _call6;
    int _call7;
    struct _4FILE** _const_get_element_ptr8;
    struct _4FILE* _load9;
    _Bool _binary_op10;
    int _call11;
    int _cx_pc = 0;
    while (1) {
        switch (_cx_pc) {
        case 0: {
    _call1 = _EN3std6string8toStringE(value);
    *(&s0) = _call1;
    _const_get_element_ptr2 = &this->file;
    _load3 = *_const_get_element_ptr2;
    _binary_op4 = _load3 == NULL;
    if (_binary_op4) {
        _cx_pc = 1;
    } else {
        _cx_pc = 2;
    }
    break;
        }
        case 1: {
    _EN3std10assertFailEP4char("Unwrap failed at FileStream.cx:21:21\n");
    _cx_pc = 2;
    break;
        }
        case 2: {
    _call5 = _EN3std12StringBuffer4sizeE((&s0));
    _call6 = _EN3std12StringBuffer4dataE((&s0));
    _call7 = fprintf(_load3, "%.*s", _call5, _call6);
    _const_get_element_ptr8 = &this->file;
    _load9 = *_const_get_element_ptr8;
    _binary_op10 = _load9 == NULL;
    if (_binary_op10) {
        _cx_pc = 3;
    } else {
        _cx_pc = 4;
    }
    break;
        }
        case 3: {
    _EN3std10assertFailEP4char("Unwrap failed at FileStream.cx:22:16\n");
    _cx_pc = 4;
    break;
        }
        case 4: {
    _call11 = fflush(_load9);
    _EN3std12StringBuffer6deinitE((&s0));
    return;
        }
        default: abort();
        }
    }
}

void _EN3std16OutputFileStream5writeI3intEEP3int(struct _16OutputFileStream* this, int* value) {
    struct _12StringBuffer s0;
    struct _12StringBuffer _call1;
    struct _4FILE** _const_get_element_ptr2;
    struct _4FILE* _load3;
    _Bool _binary_op4;
    int _call5;
    char* _call6;
    int _call7;
    struct _4FILE** _const_get_element_ptr8;
    struct _4FILE* _load9;
    _Bool _binary_op10;
    int _call11;
    int _cx_pc = 0;
    while (1) {
        switch (_cx_pc) {
        case 0: {
    _call1 = _EN3std3int8toStringE(value);
    *(&s0) = _call1;
    _const_get_element_ptr2 = &this->file;
    _load3 = *_const_get_element_ptr2;
    _binary_op4 = _load3 == NULL;
    if (_binary_op4) {
        _cx_pc = 1;
    } else {
        _cx_pc = 2;
    }
    break;
        }
        case 1: {
    _EN3std10assertFailEP4char("Unwrap failed at FileStream.cx:21:21\n");
    _cx_pc = 2;
    break;
        }
        case 2: {
    _call5 = _EN3std12StringBuffer4sizeE((&s0));
    _call6 = _EN3std12StringBuffer4dataE((&s0));
    _call7 = fprintf(_load3, "%.*s", _call5, _call6);
    _const_get_element_ptr8 = &this->file;
    _load9 = *_const_get_element_ptr8;
    _binary_op10 = _load9 == NULL;
    if (_binary_op10) {
        _cx_pc = 3;
    } else {
        _cx_pc = 4;
    }
    break;
        }
        case 3: {
    _EN3std10assertFailEP4char("Unwrap failed at FileStream.cx:22:16\n");
    _cx_pc = 4;
    break;
        }
        case 4: {
    _call11 = fflush(_load9);
    _EN3std12StringBuffer6deinitE((&s0));
    return;
        }
        default: abort();
        }
    }
}

void _EN3std16OutputFileStream5writeI4charEEP4char(struct _16OutputFileStream* this, char* value) {
    struct _12StringBuffer s0;
    struct _12StringBuffer _call1;
    struct _4FILE** _const_get_element_ptr2;
    struct _4FILE* _load3;
    _Bool _binary_op4;
    int _call5;
    char* _call6;
    int _call7;
    struct _4FILE** _const_get_element_ptr8;
    struct _4FILE* _load9;
    _Bool _binary_op10;
    int _call11;
    int _cx_pc = 0;
    while (1) {
        switch (_cx_pc) {
        case 0: {
    _call1 = _EN3std4char8toStringE(value);
    *(&s0) = _call1;
    _const_get_element_ptr2 = &this->file;
    _load3 = *_const_get_element_ptr2;
    _binary_op4 = _load3 == NULL;
    if (_binary_op4) {
        _cx_pc = 1;
    } else {
        _cx_pc = 2;
    }
    break;
        }
        case 1: {
    _EN3std10assertFailEP4char("Unwrap failed at FileStream.cx:21:21\n");
    _cx_pc = 2;
    break;
        }
        case 2: {
    _call5 = _EN3std12StringBuffer4sizeE((&s0));
    _call6 = _EN3std12StringBuffer4dataE((&s0));
    _call7 = fprintf(_load3, "%.*s", _call5, _call6);
    _const_get_element_ptr8 = &this->file;
    _load9 = *_const_get_element_ptr8;
    _binary_op10 = _load9 == NULL;
    if (_binary_op10) {
        _cx_pc = 3;
    } else {
        _cx_pc = 4;
    }
    break;
        }
        case 3: {
    _EN3std10assertFailEP4char("Unwrap failed at FileStream.cx:22:16\n");
    _cx_pc = 4;
    break;
        }
        case 4: {
    _call11 = fflush(_load9);
    _EN3std12StringBuffer6deinitE((&s0));
    return;
        }
        default: abort();
        }
    }
}

// Module 'main' forward declarations
int _EN4main3fibE3int(int n);
int main(void);
void _EN3std7printlnI3intEE3int(int value);
void _EN4main5Point4initE3int3int(struct _5Point* this, int x, int y);
_Bool _EN3std13ArrayIteratorI3intE8hasValueE(struct _13ArrayIteratorI3intE* this);
int* _EN3std13ArrayIteratorI3intE5valueE(struct _13ArrayIteratorI3intE* this);
void _EN3std13ArrayIteratorI3intE9incrementE(struct _13ArrayIteratorI3intE* this);
void _EN3std5printI3intEE3int(int value);
void _EN3std5printI4charEE4char(char value);
void _EN3std12StringBuffer6deinitE(struct _12StringBuffer* this);
struct _12StringBuffer _EN3std3int8toStringE(int* this);
int _EN3std12StringBuffer4sizeE(struct _12StringBuffer* this);
char* _EN3std12StringBuffer4dataE(struct _12StringBuffer* this);

// Module 'main' definitions

int _EN4main3fibE3int(int n) {
    _Bool _binary_op0;
    int _binary_op1;
    int _call2;
    int _binary_op3;
    int _call4;
    int _binary_op5;
    int _cx_pc = 0;
    while (1) {
        switch (_cx_pc) {
        case 0: {
    _binary_op0 = n < 2;
    if (_binary_op0) {
        _cx_pc = 1;
    } else {
        _cx_pc = 2;
    }
    break;
        }
        case 1: {
    return n;
        }
        case 2: {
    _cx_pc = 3;
    break;
        }
        case 3: {
    _binary_op1 = n - 1;
    _call2 = _EN4main3fibE3int(_binary_op1);
    _binary_op3 = n - 2;
    _call4 = _EN4main3fibE3int(_binary_op3);
    _binary_op5 = _call2 + _call4;
    return _binary_op5;
        }
        default: abort();
        }
    }
}

int main(void) {
    int sum0;
    int i1;
    struct _5Point p2;
    int arr3[5];
    int prod4;
    struct _13ArrayIteratorI3intE __iterator5;
    int* x6;
    int _load7;
    _Bool _binary_op8;
    int _load9;
    int _load10;
    int _binary_op11;
    int _load12;
    int _binary_op13;
    int _load14;
    int _call15;
    int* _const_get_element_ptr16;
    int _load17;
    int* _const_get_element_ptr18;
    int _load19;
    int _binary_op20;
    int* _const_get_element_ptr21;
    int _load22;
    int* _const_get_element_ptr23;
    int _load24;
    int _binary_op25;
    int _binary_op26;
    int _insert27[5];
    int _insert28[5];
    int _insert29[5];
    int _insert30[5];
    int _insert31[5];
    int* _const_get_element_ptr32;
    int* _get_element_ptr33;
    struct _13ArrayIteratorI3intE _insert34;
    struct _13ArrayIteratorI3intE _insert35;
    _Bool _call36;
    int* _call37;
    int _load38;
    int* _load39;
    int _load40;
    int _binary_op41;
    int _load42;
    int _cx_pc = 0;
    while (1) {
        switch (_cx_pc) {
        case 0: {
    *(&sum0) = 0;
    *(&i1) = 0;
    _cx_pc = 1;
    break;
        }
        case 1: {
    _load7 = *(&i1);
    _binary_op8 = _load7 < 10;
    if (_binary_op8) {
        _cx_pc = 2;
    } else {
        _cx_pc = 4;
    }
    break;
        }
        case 2: {
    _load9 = *(&sum0);
    _load10 = *(&i1);
    _binary_op11 = _load9 + _load10;
    *(&sum0) = _binary_op11;
    _cx_pc = 3;
    break;
        }
        case 3: {
    _load12 = *(&i1);
    _binary_op13 = _load12 + 1;
    *(&i1) = _binary_op13;
    _cx_pc = 1;
    break;
        }
        case 4: {
    _load14 = *(&sum0);
    _EN3std7printlnI3intEE3int(_load14);
    _call15 = _EN4main3fibE3int(20);
    _EN3std7printlnI3intEE3int(_call15);
    _EN4main5Point4initE3int3int((&p2), 3, 4);
    _const_get_element_ptr16 = &(&p2)->x;
    _load17 = *_const_get_element_ptr16;
    _const_get_element_ptr18 = &(&p2)->x;
    _load19 = *_const_get_element_ptr18;
    _binary_op20 = _load17 * _load19;
    _const_get_element_ptr21 = &(&p2)->y;
    _load22 = *_const_get_element_ptr21;
    _const_get_element_ptr23 = &(&p2)->y;
    _load24 = *_const_get_element_ptr23;
    _binary_op25 = _load22 * _load24;
    _binary_op26 = _binary_op20 + _binary_op25;
    _EN3std7printlnI3intEE3int(_binary_op26);
    _insert27[0] = 1;
    memcpy(&_insert28, &_insert27, sizeof(_insert28)); _insert28[1] = 2;
    memcpy(&_insert29, &_insert28, sizeof(_insert29)); _insert29[2] = 3;
    memcpy(&_insert30, &_insert29, sizeof(_insert30)); _insert30[3] = 4;
    memcpy(&_insert31, &_insert30, sizeof(_insert31)); _insert31[4] = 5;
    memcpy((&arr3), &_insert31, sizeof(_insert31));
    *(&prod4) = 1;
    _const_get_element_ptr32 = &(&arr3)[0][0];
    _get_element_ptr33 = &(_const_get_element_ptr32[5]);
    _insert34.current = _const_get_element_ptr32;
    memcpy(&_insert35, &_insert34, sizeof(_insert35)); _insert35.end = _get_element_ptr33;
    *(&__iterator5) = _insert35;
    _cx_pc = 5;
    break;
        }
        case 5: {
    _call36 = _EN3std13ArrayIteratorI3intE8hasValueE((&__iterator5));
    if (_call36) {
        _cx_pc = 6;
    } else {
        _cx_pc = 8;
    }
    break;
        }
        case 6: {
    _call37 = _EN3std13ArrayIteratorI3intE5valueE((&__iterator5));
    *(&x6) = _call37;
    _load38 = *(&prod4);
    _load39 = *(&x6);
    _load40 = *_load39;
    _binary_op41 = _load38 * _load40;
    *(&prod4) = _binary_op41;
    _cx_pc = 7;
    break;
        }
        case 7: {
    _EN3std13ArrayIteratorI3intE9incrementE((&__iterator5));
    _cx_pc = 5;
    break;
        }
        case 8: {
    _load42 = *(&prod4);
    _EN3std7printlnI3intEE3int(_load42);
    return 0;
        }
        default: abort();
        }
    }
}

void _EN3std7printlnI3intEE3int(int value) {
    int _cx_pc = 0;
    while (1) {
        switch (_cx_pc) {
        case 0: {
    _EN3std5printI3intEE3int(value);
    _EN3std5printI4charEE4char(10);
    return;
        }
        default: abort();
        }
    }
}

void _EN4main5Point4initE3int3int(struct _5Point* this, int x, int y) {
    int* _const_get_element_ptr0;
    int* _const_get_element_ptr1;
    int _cx_pc = 0;
    while (1) {
        switch (_cx_pc) {
        case 0: {
    _const_get_element_ptr0 = &this->x;
    *_const_get_element_ptr0 = x;
    _const_get_element_ptr1 = &this->y;
    *_const_get_element_ptr1 = y;
    return;
        }
        default: abort();
        }
    }
}

_Bool _EN3std13ArrayIteratorI3intE8hasValueE(struct _13ArrayIteratorI3intE* this) {
    int** _const_get_element_ptr0;
    int* _load1;
    int** _const_get_element_ptr2;
    int* _load3;
    _Bool _binary_op4;
    int _cx_pc = 0;
    while (1) {
        switch (_cx_pc) {
        case 0: {
    _const_get_element_ptr0 = &this->current;
    _load1 = *_const_get_element_ptr0;
    _const_get_element_ptr2 = &this->end;
    _load3 = *_const_get_element_ptr2;
    _binary_op4 = _load1 != _load3;
    return _binary_op4;
        }
        default: abort();
        }
    }
}

int* _EN3std13ArrayIteratorI3intE5valueE(struct _13ArrayIteratorI3intE* this) {
    int** _const_get_element_ptr0;
    int* _load1;
    int _cx_pc = 0;
    while (1) {
        switch (_cx_pc) {
        case 0: {
    _const_get_element_ptr0 = &this->current;
    _load1 = *_const_get_element_ptr0;
    return _load1;
        }
        default: abort();
        }
    }
}

void _EN3std13ArrayIteratorI3intE9incrementE(struct _13ArrayIteratorI3intE* this) {
    int** _const_get_element_ptr0;
    int* _load1;
    int* _get_element_ptr2;
    int _cx_pc = 0;
    while (1) {
        switch (_cx_pc) {
        case 0: {
    _const_get_element_ptr0 = &this->current;
    _load1 = *_const_get_element_ptr0;
    _get_element_ptr2 = &(_load1[1]);
    *_const_get_element_ptr0 = _get_element_ptr2;
    return;
        }
        default: abort();
        }
    }
}

void _EN3std5printI3intEE3int(int value) {
    struct _12StringBuffer s0;
    int _alloca1;
    struct _12StringBuffer _call2;
    int _call3;
    char* _call4;
    int _call5;
    int _cx_pc = 0;
    while (1) {
        switch (_cx_pc) {
        case 0: {
    *(&_alloca1) = value;
    _call2 = _EN3std3int8toStringE((&_alloca1));
    *(&s0) = _call2;
    _call3 = _EN3std12StringBuffer4sizeE((&s0));
    _call4 = _EN3std12StringBuffer4dataE((&s0));
    _call5 = printf("%.*s", _call3, _call4);
    _EN3std12StringBuffer6deinitE((&s0));
    return;
        }
        default: abort();
        }
    }
}

