#!/usr/bin/env python3
"""Generate the Windows OpenGL loader from the POSIX extern declarations.

Usage:
    scripts/generate-gl-loader.py

opengl32.lib only exports OpenGL 1.1, so modern entry points must be loaded
at runtime with wglGetProcAddress. vendor/gl/gl-loader.cx (Windows only)
holds one function pointer, one plain-named wrapper, and one load line per
OpenGL function, plus the loader itself; examples call loadGL() once their
context is current (a no-op on POSIX, where OpenGL links directly).

The extern declarations are the single source of truth and live in
vendor/gl/gl-extern.cx; this script regenerates gl-loader.cx from them.
It is idempotent: run it after editing the externs and commit the result.
On its first run it also performs the one-time split, moving the externs
out of vendor/gl/gl.cx into gl-extern.cx.
"""

import os
import re
import sys

EXTERN_RE = re.compile(r"extern\s+(.*\S)\s+([A-Za-z_]\w*)\((.*)\);$")

VENDOR_DIR = os.path.join(os.path.dirname(__file__), "..", "vendor", "gl")
GL_CX = os.path.join(VENDOR_DIR, "gl.cx")
GL_EXTERN_CX = os.path.join(VENDOR_DIR, "gl-extern.cx")
GL_LOADER_CX = os.path.join(VENDOR_DIR, "gl-loader.cx")

GENERATED_NOTICE = (
    "// Generated by scripts/generate-gl-loader.py from the extern\n"
    "// declarations in gl-extern.cx; do not edit by hand.\n"
)


def parse_externs(lines):
    """Parse (docs, return type, name, params) for each extern declaration."""
    externs = []
    for index, line in enumerate(lines):
        match = EXTERN_RE.match(line)
        if not match:
            continue
        ret, name, params = match.groups()
        assert "(" not in params and ")" not in params, f"nested parens: {line}"
        assert "..." not in params, f"variadic function: {line}"
        assert name.startswith("gl"), f"unexpected name: {line}"
        parsed = []
        if params.strip() not in ("", "void"):
            for param in params.split(","):
                parts = param.strip().split()
                assert len(parts) >= 2, f"unnamed parameter: {line}"
                parsed.append((" ".join(parts[:-1]), parts[-1]))
        docs = []
        cursor = index - 1
        while cursor >= 0 and lines[cursor].startswith("///"):
            docs.append(lines[cursor])
            cursor -= 1
        externs.append((list(reversed(docs)), ret, name, parsed, line))
    return externs


def fn_type(ret, params):
    return f"{ret}({', '.join(ptype for ptype, _ in params)})"


def emit_loader(externs):
    out = [GENERATED_NOTICE.rstrip("\n"), "", "#if Windows",
           "// Windows loads modern OpenGL at runtime: opengl32.lib only",
           "// exports 1.1, so each entry point below is a wrapper around a",
           "// function pointer filled in by loadGL().",
           "",
           "private extern void*? wglGetProcAddress(char* procName);",
           "private extern void*? GetModuleHandleA(char* moduleName);",
           "private extern void*? GetProcAddress(void*? moduleHandle, char* procName);",
           "",
           "// Reinterprets a loaded address as a function pointer. cast<>",
           "// rejects function types, so this goes through a union.",
           "private union ProcTransmute<T> {",
           "    void*? ptr;",
           "    T func;",
           "}",
           "",
           "private T procTransmute<T>(void*? p) {",
           "    ProcTransmute<T> u = undefined;",
           "    u.ptr = p;",
           "    return u.func;",
           "}",
           "",
           "// wglGetProcAddress reports failure as null or as one of the",
           "// small sentinel values 1, 2, 3, or -1.",
           "private bool isMissingProc(void*? proc) {",
           "    if proc == null return true;",
           "    if cast<int64>(proc) == -1 return true;",
           "    var addr = cast<c_size_t>(proc);",
           "    return addr == 1 || addr == 2 || addr == 3;",
           "}",
           "",
           "private void*? loadProc(char* name) {",
           "    var proc = wglGetProcAddress(name);",
           "    if isMissingProc(proc) {",
           '        // wglGetProcAddress fails for 1.1 entry points, which live',
           "        // in opengl32.dll itself.",
           '        proc = GetProcAddress(GetModuleHandleA("opengl32.dll"), name);',
           "    }",
           "    if isMissingProc(proc) {",
           '        abort("missing OpenGL entry point: ", string(name));',
           "    }",
           "    return proc;",
           "}",
           ""]
    for _, ret, name, params, _ in externs:
        out.append(f"private {fn_type(ret, params)} ptr_{name} = undefined;")
    out.append("")
    for docs, ret, name, params, _ in externs:
        out.extend(docs)
        out.append(f"{ret} {name}({', '.join(f'{ptype} {pname}' for ptype, pname in params)}) {{")
        call = f"ptr_{name}({', '.join(pname for _, pname in params)})"
        out.append(f"    {'return ' if ret != 'void' else ''}{call};")
        out.append("}")
        out.append("")
    out.append("// Loads every entry point for the current context. Call again")
    out.append("// after making another context current (pointer values may vary).")
    out.append("void loadGL() {")
    for _, ret, name, params, _ in externs:
        out.append(f'    ptr_{name} = procTransmute<{fn_type(ret, params)}>(loadProc("{name}"));')
    out.append("}")
    out.append("#endif")
    out.append("")
    return "\n".join(out)


def emit_extern_file(externs):
    out = ["// The OpenGL extern declarations: the single source of truth behind",
           "// gl-loader.cx. Edit by hand (shared decls live in gl.cx), then run",
           "// scripts/generate-gl-loader.py to regenerate the Windows loader.",
           "", "#if !Windows"]
    for docs, _, _, _, line in externs:
        out.extend(docs)
        out.append(line)
        out.append("")
    out.append("// No-op on POSIX: OpenGL links directly, so there is nothing to load.")
    out.append("void loadGL() {")
    out.append("}")
    out.append("#endif")
    out.append("")
    return "\n".join(out)


def main():
    # Reads use universal newlines (tolerating CRLF checkouts); writes pin
    # newline="\n" to keep the output LF on every platform.
    with open(GL_CX) as file:
        gl_lines = file.read().split("\n")
    if any(EXTERN_RE.match(line) for line in gl_lines):
        # One-time split: move the externs out of gl.cx. The remaining
        # declarations must be untouched apart from blank-line collapsing
        # where the externs (and their doc comments) were removed.
        assert not re.search(r"\n{3,}", "\n".join(gl_lines)), "unexpected blank runs in gl.cx"
        externs = parse_externs(gl_lines)
        assert externs, "no externs found in gl.cx"
        removed = set()
        for index, line in enumerate(gl_lines):
            if EXTERN_RE.match(line):
                removed.add(index)
                cursor = index - 1
                while cursor >= 0 and gl_lines[cursor].startswith("///"):
                    removed.add(cursor)
                    cursor -= 1
        stripped = [line for index, line in enumerate(gl_lines) if index not in removed]
        stripped_gl = re.sub(r"\n{3,}", "\n\n", "\n".join(stripped))
        with open(GL_CX, "w", newline="\n") as file:
            file.write(stripped_gl)
        with open(GL_EXTERN_CX, "w", newline="\n") as file:
            file.write(emit_extern_file(externs))
        print(f"split {len(externs)} externs out of gl.cx into gl-extern.cx")
    else:
        with open(GL_EXTERN_CX) as file:
            externs = parse_externs(file.read().split("\n"))
        assert externs, "no externs found in gl-extern.cx"
    with open(GL_LOADER_CX, "w", newline="\n") as file:
        file.write(emit_loader(externs))
    print(f"wrote {GL_LOADER_CX} ({len(externs)} functions)")


if __name__ == "__main__":
    sys.exit(main())
