// Site-wide docs search. The index (build/search-index.js, generated by
// website/generate_search_index.py) loads lazily on first use, so pages
// that are never searched pay nothing for it.
document.addEventListener("DOMContentLoaded", function() {
    var input = document.getElementById("site-search");
    var box = document.getElementById("site-search-results");
    if (!input || !box) return;

    var index = null;
    var indexFailed = false;
    var pendingLoads = null;
    var lastHits = [];

    // Site root derived from the home link, whose relative href the build
    // already corrected for the current page's depth.
    function siteRoot() {
        var home = document.querySelector(".top-nav h1 a");
        var root = new URL(home.getAttribute("href"), window.location.href).href;
        return root.endsWith("/") ? root : root + "/";
    }

    function loadIndex(callback) {
        if (index) {
            callback();
            return;
        }
        if (indexFailed) return;
        if (pendingLoads) {
            pendingLoads.push(callback);
            return;
        }
        pendingLoads = [callback];
        // The index sits next to this script; reuse its (depth-corrected)
        // URL instead of recomputing the page depth.
        var tag = document.querySelector('script[src$="search.js"]');
        var url = tag ? tag.getAttribute("src").replace(/search\.js$/, "search-index.js") : "search-index.js";
        var script = document.createElement("script");
        script.src = url;
        script.onload = function() {
            index = typeof CxSearchIndex !== "undefined" ? CxSearchIndex : [];
            var callbacks = pendingLoads;
            pendingLoads = null;
            callbacks.forEach(function(done) {
                done();
            });
        };
        script.onerror = function() {
            indexFailed = true;
            pendingLoads = null;
            box.innerHTML = "";
            var note = document.createElement("div");
            note.className = "search-failure";
            note.textContent = "Search is unavailable.";
            box.appendChild(note);
            box.hidden = false;
        };
        document.head.appendChild(script);
    }

    function searchTerms(query) {
        return query
            .toLowerCase()
            .split(/\s+/)
            .filter(function(term) {
                return term;
            });
    }

    // Every term must occur in the title or body; title matches rank first,
    // then earliest match wins.
    function search(query) {
        var terms = searchTerms(query);
        if (!terms.length) return [];
        var hits = [];
        for (var i = 0; i < index.length; i++) {
            var page = index[i];
            var haystack = (page.title + " " + page.text).toLowerCase();
            var earliest = -1;
            var matched = true;
            for (var t = 0; t < terms.length; t++) {
                var at = haystack.indexOf(terms[t]);
                if (at < 0) {
                    matched = false;
                    break;
                }
                if (earliest < 0 || at < earliest) earliest = at;
            }
            if (!matched) continue;
            var title = page.title.toLowerCase();
            var titleHit = terms.every(function(term) {
                return title.indexOf(term) >= 0;
            });
            hits.push({ page: page, titleHit: titleHit, at: earliest });
        }
        hits.sort(function(a, b) {
            if (a.titleHit !== b.titleHit) return a.titleHit ? -1 : 1;
            return a.at - b.at;
        });
        return hits.slice(0, 8);
    }

    function snippet(page, terms) {
        var lower = page.text.toLowerCase();
        var at = -1;
        for (var t = 0; t < terms.length; t++) {
            var found = lower.indexOf(terms[t]);
            if (found >= 0 && (at < 0 || found < at)) at = found;
        }
        if (at < 0) return page.text.slice(0, 120);
        var start = Math.max(0, at - 40);
        var end = Math.min(page.text.length, at + 80);
        return (start > 0 ? "..." : "") + page.text.slice(start, end) + (end < page.text.length ? "..." : "");
    }

    function appendHighlighted(parent, text, terms) {
        var lower = text.toLowerCase();
        var at = -1;
        var term = "";
        for (var t = 0; t < terms.length; t++) {
            var found = lower.indexOf(terms[t]);
            if (found >= 0 && (at < 0 || found < at)) {
                at = found;
                term = terms[t];
            }
        }
        if (at < 0) {
            parent.textContent = text;
            return;
        }
        parent.appendChild(document.createTextNode(text.slice(0, at)));
        var mark = document.createElement("mark");
        mark.textContent = text.slice(at, at + term.length);
        parent.appendChild(mark);
        parent.appendChild(document.createTextNode(text.slice(at + term.length)));
    }

    function clearResults() {
        lastHits = [];
        box.innerHTML = "";
        box.hidden = true;
    }

    function render(query) {
        var terms = searchTerms(query);
        if (!terms.length) {
            clearResults();
            return;
        }
        box.innerHTML = "";
        lastHits = search(query);
        if (!lastHits.length) {
            var empty = document.createElement("div");
            empty.className = "search-empty";
            empty.textContent = "No results.";
            box.appendChild(empty);
        }
        var root = siteRoot();
        for (var i = 0; i < lastHits.length; i++) {
            var page = lastHits[i].page;
            var link = document.createElement("a");
            link.href = root + page.id;
            var title = document.createElement("div");
            title.className = "result-title";
            title.textContent = page.title;
            var snip = document.createElement("div");
            snip.className = "result-snippet";
            appendHighlighted(snip, snippet(page, terms), terms);
            link.appendChild(title);
            link.appendChild(snip);
            box.appendChild(link);
        }
        box.hidden = false;
    }

    var timer = null;
    input.addEventListener("input", function() {
        clearTimeout(timer);
        timer = setTimeout(function() {
            if (!input.value.trim()) {
                clearResults();
                return;
            }
            loadIndex(function() {
                render(input.value);
            });
        }, 150);
    });
    input.addEventListener("focus", function() {
        // Reopen results dismissed by clicking away; cleared queries
        // (Escape, empty input) leave nothing to reopen.
        if (box.children.length) box.hidden = false;
    });
    input.addEventListener("keydown", function(event) {
        if (event.key === "Escape") {
            input.value = "";
            clearResults();
        } else if (event.key === "Enter" && lastHits.length) {
            window.location.href = siteRoot() + lastHits[0].page.id;
        }
    });
    document.addEventListener("click", function(event) {
        if (!event.target.closest(".search")) {
            box.hidden = true;
        }
    });
});
